### ISSUE TITLE
rpc url for mainnet and testnet not working

### ISSUE THREAD

**Issue by LeeDewyze** [hashgraph/hedera-json-rpc-relay#1080]
### Description

https://mainnet.hashio.io/api https://testnet.hashio.io/api The rpc url of the mainnet and test network often reports an error, and the rpc url cannot be used to deploy the contract normally

### Steps to reproduce

1.  deploy contract with Hardhat
2. run "npx hardhat run scripts/deployContract.js"

### Additional context

![image](https://user-images.githubusercontent.com/1024158/232233290-bc42ff12-1013-42dc-b888-29b8bcd0f1ef.png)

```logs=
Error: bad response (status=502, headers={"date":"Sat, 15 Apr 2023 14:44:35 GMT","content-type":"text/html; charset=UTF-8","transfer-encoding":"chunked","connection":"close","referrer-policy":"no-referrer","cf-cache-status":"DYNAMIC","server":"cloudflare","cf-ray":"7b84f6ee2f5a30ac-SEA"}, body="\n<html><head>\n<meta http-equiv=\"content-type\" content=\"text/html;charset=utf-8\">\n<title>502 Server Error</title>\n</head>\n<body text=#000000 bgcolor=#ffffff>\n<h1>Error: Server Error</h1>\n<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>\n<h2></h2>\n</body></html>\n", requestBody="{\"method\":\"eth_getBlockByNumber\",\"params\":[\"latest\",false],\"id\":45,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://testnet.hashio.io/api", code=SERVER_ERROR, version=web/5.7.1)
    at Logger.makeError (/Users/liaiguo/digital/projects/arbitrage/hedera-contract-template/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
    at Logger.throwError (/Users/liaiguo/digital/projects/arbitrage/hedera-contract-template/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
    at /Users/liaiguo/digital/projects/arbitrage/hedera-contract-template/node_modules/@ethersproject/web/src.ts/index.ts:308:24
    at step (/Users/liaiguo/digital/projects/arbitrage/hedera-contract-template/node_modules/@ethersproject/web/lib/index.js:33:23)
    at Object.next (/Users/liaiguo/digital/projects/arbitrage/hedera-contract-template/node_modules/@ethersproject/web/lib/index.js:14:53)
    at fulfilled (/Users/liaiguo/digital/projects/arbitrage/hedera-contract-template/node_modules/@ethersproject/web/lib/index.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'bad response',
  code: 'SERVER_ERROR',
  status: 502,
  headers: {
    date: 'Sat, 15 Apr 2023 14:44:35 GMT',
    'content-type': 'text/html; charset=UTF-8',
    'transfer-encoding': 'chunked',
    connection: 'close',
    'referrer-policy': 'no-referrer',
    'cf-cache-status': 'DYNAMIC',
    server: 'cloudflare',
    'cf-ray': '7b84f6ee2f5a30ac-SEA'
  },
  body: '\n' +
    '<html><head>\n' +
    '<meta http-equiv="content-type" content="text/html;charset=utf-8">\n' +
    '<title>502 Server Error</title>\n' +
    '</head>\n' +
    '<body text=#000000 bgcolor=#ffffff>\n' +
    '<h1>Error: Server Error</h1>\n' +
    '<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>\n' +
    '<h2></h2>\n' +
    '</body></html>\n',
  requestBody: '{"method":"eth_getBlockByNumber","params":["latest",false],"id":45,"jsonrpc":"2.0"}',
  requestMethod: 'POST',
  url: 'https://testnet.hashio.io/api'
}
```

### Hedera network

mainnet, testnet

### Version

hardhat ^2.12.0  @hashgraph/hethers ^1.1.2

### Operating system

macOS

**Comment by georgi-l95** [comment]
Hey @LeeDewyze can you reproduce this behaviour? There was temporary issue, which was fixed.

**Comment by Kalina-Todorova** [comment]
Hi @LeeDewyze as per above comment, hoping this got resolved for you! Feel free to reopen if you face this issue again.
