### ISSUE TITLE
Fix Dapp flaky tests

### ISSUE THREAD

**Issue by georgi-l95** [hashgraph/hedera-json-rpc-relay#1171]
### Description

Occasionally dapp tests are failing in the Ci, as well against previewnet and testnet.
1. : 

```
MetaMask - RPC Error: [ethjs-query] while formatting outputs from RPC:
 '{"value": {"code":-32603,"data":{"jsonrpc":"2.0","id":4062941015442,"error":{"code":-32009,"name":"Gas price too low","message":"[Request ID: 69891d94-c987-4289-9f77-a4a798080c7a] Gas price below configured minimum gas price"}}}}' 
```
Relay stack trace: 

```
[2023-05-04 12:06:22.425 +0000] TRACE (relay-eth/55187 on Georgis-MacBook-Pro-4.local): [Request ID: 69891d94-c987-4289-9f77-a4a798080c7a] Nonce precheck for sendRawTransaction(tx.nonce=3, accountInfoNonce=3)
[2023-05-04 12:06:22.425 +0000] TRACE (relay-eth/55187 on Georgis-MacBook-Pro-4.local): [Request ID: 69891d94-c987-4289-9f77-a4a798080c7a] Failed gas price precheck for sendRawTransaction(transaction={"type":2,"chainId":297,"nonce":3,"maxPriorityFeePerGas":{"type":"BigNumber","hex":"0x00"},"maxFeePerGas":{"type":"BigNumber","hex":"0x00"},"gasPrice":null,"gasLimit":{"type":"BigNumber","hex":"0x0927c0"},"to":"0x54C51b7637BF6fE9709e1e0EBc8b2Ca6a24b0f0A","value":{"type":"BigNumber","hex":"0x2386f26fc10000"},"data":"0x","accessList":[],"hash":"0xcf2bedcec1441b0af7d09f71ea532e8b8c125b42058654eed6b7097392ab4dc9","v":0,"r":"0xf16961a574e869a20f79005d7c29f714943880c7effdd9d9e87224cbcfacecd4","s":"0x05aa2f04345386d92428fecd19b3d8cb882a5c9eb6ca53ad5e6b85f7ea354289","from":"0x437D94af6c837E4592eCF1488EB81114DFAb57Bd"}, gasPrice=0, requiredGasPrice=710000000000)
[2023-05-04 12:06:22.425 +0000] WARN (relay-eth/55187 on Georgis-MacBook-Pro-4.local): [Request ID: 69891d94-c987-4289-9f77-a4a798080c7a] Error on precheck sendRawTransaction(from=0x437D94af6c837E4592eCF1488EB81114DFAb57Bd, to=0x54C51b7637BF6fE9709e1e0EBc8b2Ca6a24b0f0A, transaction=0x02f86c820129038080830927c09454c51b7637bf6fe9709e1e0ebc8b2ca6a24b0f0a872386f26fc1000080c080a0f16961a574e869a20f79005d7c29f714943880c7effdd9d9e87224cbcfacecd4a005aa2f04345386d92428fecd19b3d8cb882a5c9eb6ca53ad5e6b85f7ea354289)
[2023-05-04 12:06:22.425 +0000] ERROR (Gas price too low/55187 on Georgis-MacBook-Pro-4.local):
    code: -32009
    message: "Gas price below configured minimum gas price"
[2023-05-04 12:06:22.425 +0000] ERROR (Gas price too low/55187 on Georgis-MacBook-Pro-4.local): [Request ID: 69891d94-c987-4289-9f77-a4a798080c7a] [POST] eth_sendRawTransaction: -32603 107 ms
    code: -32009
    message: "Gas price below configured minimum gas price"
[2023-05-04 12:06:22.425 +0000] ERROR (rpc-server/55187 on Georgis-MacBook-Pro-4.local): [Request ID: 69891d94-c987-4289-9f77-a4a798080c7a] returning error to sender: Gas price below configured minimum gas price
[2023-05-04 12:06:22.425 +0000] ERROR (rpc-server/55187 on Georgis-MacBook-Pro-4.local): [Request ID: 69891d94-c987-4289-9f77-a4a798080c7a] [POST] eth_sendRawTransaction: 400 (-32009) (JSON RPC ERROR) 107 ms


```

2. When we create a hollow account, we are charged gas for the creation. If we try to make second transfer, we are again charged for creation 🤔 

3. We are caching balance for account, and checking if we have cached balance before returing it. However we are returning undefined for some reason:
```
[2023-05-04 12:44:22.235 +0000] DEBUG (mirror-node/55187 on Georgis-MacBook-Pro-4.local): [Request ID: 520e77a4-48f3-4708-a210-e662fc748e3b] [GET] accounts/0xb82ed18687bf8a7626678f3c3fc686f2befd589f?limit=100 200 216 ms
[2023-05-04 12:44:22.236 +0000] TRACE (relay-eth/55187 on Georgis-MacBook-Pro-4.local): [Request ID: 520e77a4-48f3-4708-a210-e662fc748e3b] caching eth_get_balance-0xb82ed18687bf8a7626678f3c3fc686f2befd589f-latest:undefined for 1000 ms
```
This trace is only generated for successful getBalance return. undefined in this case is returned cached balance.

### Steps to reproduce

1. Run the dapp tests in CI

### Hedera network

testnet, previewnet, other

### Version

latest

### Operating system

None

**Comment by georgi-l95** [comment]
```[2023-05-22 11:40:25.529 +0000] ERROR (relay-eth/35808 on Georgis-MacBook-Pro-4.local): [Request ID: 0d877a6d-939d-4dcb-bfb2-e0f5b993cbec] Failed to successfully submit sendRawTransaction for transaction 0x02f8b3820129028459682f0085c6b890770083061a80940000000000000000000000000000000000007bc380b844a9059cbb00000000000000000000000054c51b7637bf6fe9709e1e0ebc8b2ca6a24b0f0a00000000000000000000000000000000000000000000000000000000000003e8c001a08dc184e26b57247dcb0a2026d1edfe59ab6d376962eb621bdf2eba60c92caddda0304ada7a23658461cf997b9c0f8ab4639a26575671edff5db63305f9104bb3bd
    err: {
      "type": "TypeError",
      "message": "Cannot read properties of null (reading 'transactions')",
      "stack":
          TypeError: Cannot read properties of null (reading 'transactions')
              at EthImpl.<anonymous> (/Users/georgi-lazarov/Documents/GitHub/hedera-json-rpc-relay/packages/relay/dist/lib/eth.js:991:28)
              at Generator.next (<anonymous>)
              at fulfilled (/Users/georgi-lazarov/Documents/GitHub/hedera-json-rpc-relay/packages/relay/dist/lib/eth.js:24:58)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    }
[2023-05-22 11:40:25.529 +0000] INFO (rpc-server/35808 on Georgis-MacBook-Pro-4.local): [Request ID: 0d877a6d-939d-4dcb-bfb2-e0f5b993cbec] [POST] eth_sendRawTransaction: -32603 848 ms 
[2023-05-22 11:40:25.529 +0000] ERROR (rpc-server/35808 on Georgis-MacBook-Pro-4.local): [Request ID: 0d877a6d-939d-4dcb-bfb2-e0f5b993cbec] returning error to sender: Error invoking RPC: Cannot read properties of null (reading 'transactions')
```

**Comment by Kalina-Todorova** [comment]
Resolved with: https://github.com/hashgraph/hedera-json-rpc-relay/pull/1285
