### ISSUE TITLE
Error on EthImpl.numberTo0x() use on contract results block num 

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-json-rpc-relay#1277]
### Description

It seems for some contract results the relay is throwing errors converting the `contractResult.block_number` to a hex.
```
[POST] eth_getTransactionByHash: -32603 274 ms
    err: {
      "type": "TypeError",
      "message": "Cannot read properties of undefined (reading 'toString')",
      "stack":
          TypeError: Cannot read properties of undefined (reading 'toString')
              at EthImpl.numberTo0x (/Users/user/code/hedera/hedera-json-rpc-relay/packages/relay/dist/lib/eth.js:1129:41)
              at EthImpl.<anonymous> (/Users/user/code/hedera/hedera-json-rpc-relay/packages/relay/dist/lib/eth.js:1056:43)
              at Generator.next (<anonymous>)
              at fulfilled (/Users/user/code/hedera/hedera-json-rpc-relay/packages/relay/dist/lib/eth.js:24:58)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    }
```

Seems to map back to https://github.com/hashgraph/hedera-json-rpc-relay/blob/release/0.23/packages/relay/src/lib/eth.ts#L1312

### Steps to reproduce

This likely occurs for failed transactions of a particular  kind

1. Query `eth_getTransactionByHash` for a transaction with a null or undefined block_number 

### Hedera network

testnet

### Version

v0.23.0.5

### Operating system

None

**Comment by georgi-l95** [comment]
It appears that `block_number` is present in `contract_result` response from the mirror-node request, but when we get to when we need to format it properly it's `undefined`. Still investigating.
