### ISSUE TITLE
Add acceptance test support for eth_sendRawTransaction using an EIP 155 transaction

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-json-rpc-relay#134]
### Problem

During the setup of acceptance tests the `eth_sendRawTransaction` flow for EIP 155 produced errors.
As such it was removed.

Error was
```
    err: {
      "type": "PrecheckStatusError",
      "message": "transaction 0.0.2@1654127819.276547659 failed precheck with status WRONG_CHAIN_ID",
      "stack":
          StatusError: transaction 0.0.2@1654127819.276547659 failed precheck with status WRONG_CHAIN_ID
              at new PrecheckStatusError (.../hedera-json-rpc-relay/packages/relay/node_modules/@hashgraph/sdk/lib/PrecheckStatusError.cjs:43:5)
              at EthereumTransaction._mapStatusError (.../hedera-json-rpc-relay/packages/relay/node_modules/@hashgraph/sdk/lib/transaction/Transaction.cjs:1122:12)
              at EthereumTransaction.execute (.../hedera-json-rpc-relay/packages/relay/node_modules/@hashgraph/sdk/lib/Executable.cjs:519:22)
              at processTicksAndRejections (node:internal/process/task_queues:96:5)
      "name": "StatusError",
      "status": {
        "_code": 311
      },
``` 

### Solution

Add a test case that supports EIP_155 raw transaction submission

**Comment by Ivo-Yankov** [comment]
The relay doesn't support transactions with no `chianId` field. We have a test for that case [here:](https://github.com/hashgraph/hedera-json-rpc-relay/blob/84fffedc5f9cbe9ef449724857e01a12100dbfab/packages/server/tests/acceptance.spec.ts#L432)

**Comment by Kalina-Todorova** [comment]
Closing this one as we have it covered.
