### ISSUE TITLE
fix: unable to parse some contract transaction reverted, resulting in "TypeError: Cannot read properties of null (reading 'transactions')"

### ISSUE THREAD

**Issue by bguiz** [hashgraph/hedera-json-rpc-relay#1377]
### Description

- Be able to parse the error message, instead of "unknown error"

### Steps to reproduce

1. Submit this transaction: https://hashscan.io/testnet/transaction/1687274355.056813003
2. Observe that transaction is reverted
3. But there is no error message on Hashscan
4. Observe in browser error: `Unknown error invoking RPC` - full message copied below
5. Observe RPC relay error: `TypeError: Cannot read properties of null (reading 'transactions')` - logs copied below

### Additional context

Error message in browser (from Metamask):

```text
MetaMask - RPC Error: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"jsonrpc":"2.0","id":6696677332751,"error":{"code":-32603,"name":"Internal error","message":"[Request ID: 66de5563-d3e5-47d2-9d3d-444f557ace76] Unknown error invoking RPC"}}}}'
```

Relevant part of log output from RPC Relay:

```text
[2023-06-20 15:19:16.579 +0000] DEBUG (consensus-node/91353 on admins-MacBook-Pro.local): [Request ID: 66de5563-d3e5-47d2-9d3d-444f557ace76] 0.0.3996280@1687274343.363097580 eth_sendRawTransaction EthereumTransaction record status: CONTRACT_REVERT_EXECUTED (33), cost: 1.81207359 ℏ
[2023-06-20 15:19:17.045 +0000] TRACE (mirror-node/91353 on admins-MacBook-Pro.local): [Request ID: 66de5563-d3e5-47d2-9d3d-444f557ace76] Retry delay 250 ms
[2023-06-20 15:19:17.529 +0000] TRACE (mirror-node/91353 on admins-MacBook-Pro.local): [Request ID: 66de5563-d3e5-47d2-9d3d-444f557ace76] Retry delay 500 ms
[2023-06-20 15:19:18.110 +0000] INFO (consensus-node/91353 on admins-MacBook-Pro.local):  0.0.3996280@1687274346.358351484 eth_sendRawTransaction FileContentsQuery status: SUCCESS (22), cost: 36 tℏ
[2023-06-20 15:19:18.264 +0000] TRACE (mirror-node/91353 on admins-MacBook-Pro.local): [Request ID: 66de5563-d3e5-47d2-9d3d-444f557ace76] Retry delay 750 ms
[2023-06-20 15:19:18.556 +0000] INFO (consensus-node/91353 on admins-MacBook-Pro.local):  0.0.3996280@1687274347.117995795 eth_sendRawTransaction FileContentsQuery status: SUCCESS (22), cost: 23 tℏ
0
[2023-06-20 15:19:19.256 +0000] DEBUG (mirror-node/91353 on admins-MacBook-Pro.local): [Request ID: 66de5563-d3e5-47d2-9d3d-444f557ace76] [GET] transactions/0.0.3996280-1687274343-363097580 404 status
[2023-06-20 15:19:19.256 +0000] ERROR (relay-eth/91353 on admins-MacBook-Pro.local): [Request ID: 66de5563-d3e5-47d2-9d3d-444f557ace76] Failed to successfully submit sendRawTransaction for transaction 0x02f9013582012881828459682f0086020ad23ad70083061a80943a8bac3ce0dbe706f377600c117c9f2aed2a403680b8c4b68a4ba00000000000000000000000003a8bac3ce0dbe706f377600c117c9f2aed2a403600000000000000000000000000000000000000000000000000000002540be400000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000020000000000000000000000001c29e31d241f0d06f3763221f5224a6b82f09cce0000000000000000000000009a814b5afd6b0fff1e9548dcba4d09cdd8c81568c080a0891cfa17b17ad82645cd3fd7fa5fd782fc3f9434b87e0a751f0b691b601f28f8a020c3b646a3a276e67e2663963711f319b8a99d6ed7716c60e9a4dd5b0e953191
    err: {
      "type": "TypeError",
      "message": "Cannot read properties of null (reading 'transactions')",
      "stack":
          TypeError: Cannot read properties of null (reading 'transactions')
              at EthImpl.<anonymous> (/Users/user/code/hedera/hedera-json-rpc-relay/packages/relay/dist/lib/eth.js:878:28)
              at Generator.next (<anonymous>)
              at fulfilled (/Users/user/code/hedera/hedera-json-rpc-relay/packages/relay/dist/lib/eth.js:24:58)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    }
[2023-06-20 15:19:19.257 +0000] INFO (rpc-server/91353 on admins-MacBook-Pro.local): [Request ID: 66de5563-d3e5-47d2-9d3d-444f557ace76] [POST] eth_sendRawTransaction: -32603 2931 ms 
[2023-06-20 15:19:19.257 +0000] ERROR (rpc-server/91353 on admins-MacBook-Pro.local): [Request ID: 66de5563-d3e5-47d2-9d3d-444f557ace76] returning error to sender: Unknown error invoking RPC
[2023-06-20 15:19:19.257 +0000] ERROR (rpc-server/91353 on admins-MacBook-Pro.local): [Request ID: 66de5563-d3e5-47d2-9d3d-444f557ace76] [POST] eth_sendRawTransaction: 500 (-32603) (JSON RPC ERROR) 2931 ms
```

### Hedera network

testnet

### Version

Reproduced on both v0.25.0 and HEAD of main (46d7f485a6ec3547c9265288d13f28873b1a70cd) of the RPC relay

### Operating system

macOS

**Comment by bguiz** [comment]
Closing this issue.

Reason:
- Unable to reproduce this on latest commit of `main` branch ([`b3621e`](https://github.com/hashgraph/hedera-json-rpc-relay/commit/b3621ea7813a0223a26d1a546d6c0604f9cda5ec)).

Details:
- `eth_sendRawTransaction` now has a completely different implementation, from https://github.com/hashgraph/hedera-json-rpc-relay/pull/1345
- The above error (`TypeError: Cannot read properties of null (reading 'transactions')`) was within the previous `eth_sendRawTransaction` implementation which did not involve the mirror node (communicated with consensus nodes directly)
- The new `eth_sendRawTransaction` implementation has a different code path which invokes mirror nodes instead
- I assume that this is indirectly related to [HIP-584 - Mirror EVM Archive Node](https://hips.hedera.com/hip/hip-584), as that describes switching from consensus nodes to mirror nodes for `eth_sendRawTransaction` + adding a true `eth_estimateGas` implementation (instead of hardcoded values)

**Comment by Nana-EC** [comment]
It's likely the issue here is related to https://github.com/hashgraph/hedera-json-rpc-relay/blob/main/packages/relay/src/lib/eth.ts#L1157 where `tx` could be null yet we're still trying to get transactions out of it
