### ISSUE TITLE
Counter in Cache Client throws exception

### ISSUE THREAD

**Issue by georgi-l95** [hashgraph/hedera-json-rpc-relay#1442]
### Description

Counter in Cache client is throwing exception, when trying to report data back.

```
[2023-07-04 14:56:17.821 +0000] INFO (rpc-server/74 on b19e5f77e704): [GET]: /health/liveness 200 0 ms
      at new Promise (<anonymous>)
      at __awaiter (/home/node/app/packages/relay/dist/lib/clients/clientCache.js:23:12)
      at Counter.collect (/home/node/app/packages/relay/dist/lib/clients/clientCache.js:67:24)
      at Counter.get (/home/node/app/node_modules/prom-client/lib/counter.js:54:19)
      at Registry.getMetricAsPrometheusString (/home/node/app/node_modules/prom-client/lib/registry.js:26:29)
      at Registry.metrics (/home/node/app/node_modules/prom-client/lib/registry.js:70:23)
  TypeError: this.cacheKeyCounter.set is not a function
      at cacheSizeCollect (/home/node/app/packages/relay/dist/lib/clients/clientCache.js:57:34)
      at Counter.<anonymous> (/home/node/app/packages/relay/dist/lib/clients/clientCache.js:68:21)
      at Generator.next (<anonymous>)
      at /home/node/app/packages/relay/dist/lib/clients/clientCache.js:27:71
      at new Promise (<anonymous>)
      at __awaiter (/home/node/app/packages/relay/dist/lib/clients/clientCache.js:23:12)
      at Counter.collect (/home/node/app/packages/relay/dist/lib/clients/clientCache.js:67:24)
      at Counter.get (/home/node/app/node_modules/prom-client/lib/counter.js:54:19)
      at Registry.getMetricAsPrometheusString (/home/node/app/node_modules/prom-client/lib/registry.js:26:29)
      at Registry.metrics (/home/node/app/node_modules/prom-client/lib/registry.js:70:23)
```

### Steps to reproduce

1. Start local-node with latest relay image
2. Observe logs

### Hedera network

other

### Version

main

### Operating system

None

**Comment by georgi-l95** [comment]
Already PR for this https://github.com/hashgraph/hedera-json-rpc-relay/pull/1432
