### ISSUE TITLE
Subgraph test fails

### ISSUE THREAD

**Issue by georgi-l95** [hashgraph/hedera-json-rpc-relay#1677]
### Description

When trying to execute the steps from the subgraph example, they fail when we try to execute `npx hardhat prepare`. 
Error is:

```
Error: Cannot find module '@graphprotocol/graph-cli/src/command-helpers/spinner'
Require stack:
- /Users/georgi-lazarov/Documents/GitHub/hedera-json-rpc-relay/tools/subgraph-example/node_modules/@graphprotocol/hardhat-graph/dist/helpers/generator.js
- /Users/georgi-lazarov/Documents/GitHub/hedera-json-rpc-relay/tools/subgraph-example/node_modules/@graphprotocol/hardhat-graph/dist/tasks.js
- /Users/georgi-lazarov/Documents/GitHub/hedera-json-rpc-relay/tools/subgraph-example/node_modules/@graphprotocol/hardhat-graph/dist/index.js
- /Users/georgi-lazarov/Documents/GitHub/hedera-json-rpc-relay/tools/subgraph-example/hardhat.config.ts
- /Users/georgi-lazarov/Documents/GitHub/hedera-json-rpc-relay/tools/subgraph-example/node_modules/hardhat/internal/core/config/config-loading.js
- /Users/georgi-lazarov/Documents/GitHub/hedera-json-rpc-relay/tools/subgraph-example/node_modules/hardhat/internal/cli/cli.js
- /Users/georgi-lazarov/Documents/GitHub/hedera-json-rpc-relay/tools/subgraph-example/node_modules/hardhat/internal/cli/bootstrap.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/Users/georgi-lazarov/Documents/GitHub/hedera-json-rpc-relay/tools/subgraph-example/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/georgi-lazarov/Documents/GitHub/hedera-json-rpc-relay/tools/subgraph-example/node_modules/@graphprotocol/hardhat-graph/dist/helpers/generator.js:8:25)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Object.require.extensions.<computed> [as .js] (/Users/georgi-lazarov/Documents/GitHub/hedera-json-rpc-relay/tools/subgraph-example/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1037:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/georgi-lazarov/Documents/GitHub/hedera-json-rpc-relay/tools/subgraph-example/node_modules/@graphprotocol/hardhat-graph/dist/helpers/generator.js',
    '/Users/georgi-lazarov/Documents/GitHub/hedera-json-rpc-relay/tools/subgraph-example/node_modules/@graphprotocol/hardhat-graph/dist/tasks.js',
    '/Users/georgi-lazarov/Documents/GitHub/hedera-json-rpc-relay/tools/subgraph-example/node_modules/@graphprotocol/hardhat-graph/dist/index.js',
    '/Users/georgi-lazarov/Documents/GitHub/hedera-json-rpc-relay/tools/subgraph-example/hardhat.config.ts',
    '/Users/georgi-lazarov/Documents/GitHub/hedera-json-rpc-relay/tools/subgraph-example/node_modules/hardhat/internal/core/config/config-loading.js',
    '/Users/georgi-lazarov/Documents/GitHub/hedera-json-rpc-relay/tools/subgraph-example/node_modules/hardhat/internal/cli/cli.js',
    '/Users/georgi-lazarov/Documents/GitHub/hedera-json-rpc-relay/tools/subgraph-example/node_modules/hardhat/internal/cli/bootstrap.js'
  ]
}
```

### Steps to reproduce

1.Run `npx hardhat prepare` in subgraph dir.

### Hedera network

other

### Version

version after branch 1625-add-redis-cache-support

### Operating system

None

**Comment by georgi-l95** [comment]
This was fixed with https://github.com/hashgraph/hedera-json-rpc-relay/pull/1666
