### ISSUE TITLE
Release automation, acceptance test fails in a "beforeAll" hook for a test that's not run.

### ISSUE THREAD

**Issue by ebadiere** [hashgraph/hedera-json-rpc-relay#1724]
### Description

When running the ```acceptancetest:release``` test, an unrelated test set up can fail.  This should be fixed before adopting the acceptance tests into any automated hashio deployment process.

```
1) RPC Server Acceptance Tests
       Acceptance tests
         @api-batch-2 RPC Server Acceptance Tests
           eth_getCode
             "before all" hook for "should execute "eth_getCode" for hts token":
     Error: server response 502 Bad Gateway (request={  }, response={  }, error=null, code=SERVER_ERROR, version=6.7.1)
      at makeError (packages/server/node_modules/ethers/src.ts/utils/errors.ts:685:21)
      at assert (packages/server/node_modules/ethers/src.ts/utils/errors.ts:702:25)
      at FetchResponse.assertOk (packages/server/node_modules/ethers/src.ts/utils/fetch.ts:896:15)
      at JsonRpcProvider._send (packages/server/node_modules/ethers/src.ts/providers/provider-jsonrpc.ts:1160:18)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at /Users/user/projects/releases/hedera-json-rpc-relay/packages/server/node_modules/ethers/src.ts/providers/provider-jsonrpc.ts:500:40



[2023-09-06 23:37:06.071 +0000] INFO (rpc-acceptance-test/64575 on Admins-Laptop.hsd1.co.comcast.net): Acceptance Tests spent 778.12826277 ℏ
[2023-09-06 23:37:06.071 +0000] INFO (rpc-acceptance-test/64575 on Admins-Laptop.hsd1.co.comcast.net): Stop relay
```

### Steps to reproduce

1. Point to `previewnet`.
2. run the release acceptance tests: `npm run acceptancetest:release`

### Hedera network

previewnet

### Version

v0.31.0

### Operating system

macOS

**Comment by quiet-node** [comment]
The release test suite has been improved, and no tests have failed since version 0.66.0-rc1.
