### ISSUE TITLE
Automated Dapp acceptance tests should be able to run from the command line.

### ISSUE THREAD

**Issue by ebadiere** [hashgraph/hedera-json-rpc-relay#1725]
### Description

Commands for running the DA are listed in the CI workflow.  The command of interest runs the Dapp tests in docker containers driven by docker-compose.  The command is:
`docker-compose up --exit-code-from synpress`

On a mac this results in a core dump.  These tests will be part of the future deployment process, so this needs to be stable and work.

When running this command on a mac the following happens:
```
[STARTED] Task without title.
synpress  | [FAILED] Cypress failed to start.
synpress  | [FAILED]
synpress  | [FAILED] This may be due to a missing library or dependency. https://on.cypress.io/required-dependencies
synpress  | [FAILED]
synpress  | [FAILED] Please refer to the error below for more details.
synpress  | [FAILED]
synpress  | [FAILED] ----------
synpress  | [FAILED]
synpress  | [FAILED] qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
synpress  | [FAILED] qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
synpress  | [FAILED] qemu: uncaught target signal 11 (Segmentation fault) - core dumped
synpress  | [FAILED]
synpress  | [FAILED] ----------
synpress  | [FAILED]
synpress  | [FAILED] Platform: linux-x64 (Ubuntu - 22.04)
synpress  | [FAILED] Cypress Version: 12.13.0
synpress  | node:internal/process/promises:288
synpress  |             triggerUncaughtException(err, true /* fromPromise */);
synpress  |             ^
synpress  |
synpress  | Error: Cypress failed to start.
synpress  |
synpress  | This may be due to a missing library or dependency. https://on.cypress.io/required-dependencies
synpress  |
synpress  | Please refer to the error below for more details.
synpress  |
synpress  | ----------
synpress  |
synpress  | qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
synpress  | qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
synpress  | qemu: uncaught target signal 11 (Segmentation fault) - core dumped
synpress  |
synpress  | ----------
synpress  |
synpress  | Platform: linux-x64 (Ubuntu - 22.04)
synpress  | Cypress Version: 12.13.0
synpress  |     at /app/node_modules/cypress/lib/errors.js:328:17 {
synpress  |   known: true
synpress  | }
synpress  |
synpress  |
synpress  | Node.js v18.12.1
synpress  |
synpress  | Error: Command failed with exit code 1: npm run test
synpress  |     at makeError (/app/node_modules/start-server-and-test/node_modules/execa/lib/error.js:60:11)
synpress  |     at handlePromise (/app/node_modules/start-server-and-test/node_modules/execa/index.js:118:26)
synpress  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
synpress  |   shortMessage: 'Command failed with exit code 1: npm run test',
synpress  |   command: 'npm run test',
synpress  |   escapedCommand: '"npm run test"',
synpress  |   exitCode: 1,
synpress  |   signal: undefined,
synpress  |   signalDescription: undefined,
synpress  |   stdout: undefined,
synpress  |   stderr: undefined,
synpress  |   failed: true,
synpress  |   timedOut: false,
synpress  |   isCanceled: false,
synpress  |   killed: false
synpress  | }
synpress exited with code 1
Aborting on container exit...
[+] Stopping 2/2
 ✔ Container synpress  Stopped                                                                                                                                                                                  0.0s
 ✔ Container display   Stopped
```

### Steps to reproduce

1. Set up a. env file to point to previewnet
2. Run each command as it is listed in the CI workflow
3. The docker compose command is the command that triggers the error:
```
- name: Build, Bootstrap & Test the dapp in Docker
        run: docker-compose up --exit-code-from synpress
        working-directory: ./dapp-example/
```

### Hedera network

previewnet

### Version

v0.31.1

### Operating system

macOS

**Comment by ebadiere** [comment]
Dapp tests can run from the command line and regularly pass when running on previewnet.  Issue #2029 covers the instability running on testnet from the local command line.
