### ISSUE TITLE
AcceptanceTest TokenCreate is Consistently Failing

### ISSUE THREAD

**Issue by AlfredoG87** [hashgraph/hedera-json-rpc-relay#1913]
### Description

When running the test: `acceptancetest:tokencreate`
The following error is happening, all the time: 

```
1) RPC Server Acceptance Tests
       Acceptance tests
         @tokencreate HTS Precompile Token Create Acceptance Tests
           "before all" hook for "should associate to a token":
     Error: invalid value for value.hash (Cannot read properties of null (reading 'hash')) (value=null, code=BAD_DATA, version=6.8.1)
      at makeError (packages/server/node_modules/ethers/src.ts/utils/errors.ts:694:21)
      at assert (packages/server/node_modules/ethers/src.ts/utils/errors.ts:715:25)
      at /home/runner/work/hedera-json-rpc-relay/hedera-json-rpc-relay/packages/server/node_modules/ethers/src.ts/providers/format.ts:58:23
      at formatBlock (packages/server/node_modules/ethers/src.ts/providers/format.ts:129:20)
      at JsonRpcProvider._wrapBlock (packages/server/node_modules/ethers/src.ts/providers/abstract-provider.ts:629:37)
      at getFeeDataFunc (packages/server/node_modules/ethers/src.ts/providers/abstract-provider.ts:914:32)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at JsonRpcProvider.getFeeData (packages/server/node_modules/ethers/src.ts/providers/abstract-provider.ts:931:16)
      at Wallet.populateTransaction (packages/server/node_modules/ethers/src.ts/providers/abstract-signer.ts:144:29)
      at Wallet.sendTransaction (packages/server/node_modules/ethers/src.ts/providers/abstract-signer.ts:232:21)
      at ContractFactory.deploy (packages/server/node_modules/ethers/src.ts/contract/factory.ts:111:24)

```

### Steps to reproduce

Run:

`npm run acceptancetest:tokencreate`

### Hedera network

other

### Version

v0.36.0

### Operating system

None

**Comment by AlfredoG87** [comment]
![Image](https://github.com/hashgraph/hedera-json-rpc-relay/assets/123040664/02d1b4d1-94bc-4a3b-820f-b51a2a2f64d9)
