### ISSUE TITLE
Acceptance Tests Flakyness - WebSocket

### ISSUE THREAD

**Issue by AlfredoG87** [hashgraph/hedera-json-rpc-relay#1919]
### Description

a lot of times this 2 tests are failing, after a couple retries it passes.

```
  31 passing (6m)
  2 failing

  1) RPC Server Acceptance Tests
       Acceptance tests
         @web-socket Acceptance Tests
           Subscribes to hts tokens and listens for synthetic log events
             @release captures transfer events:
     Error: server response 500 Internal Server Error (request={  }, response={  }, error=null, code=SERVER_ERROR, version=6.8.1)
      at makeError (packages/server/node_modules/ethers/src.ts/utils/errors.ts:694:21)
      at assert (packages/server/node_modules/ethers/src.ts/utils/errors.ts:715:25)
      at FetchResponse.assertOk (packages/server/node_modules/ethers/src.ts/utils/fetch.ts:939:15)
      at JsonRpcProvider._send (packages/server/node_modules/ethers/src.ts/providers/provider-jsonrpc.ts:1160:18)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at /home/runner/work/hedera-json-rpc-relay/hedera-json-rpc-relay/packages/server/node_modules/ethers/src.ts/providers/provider-jsonrpc.ts:500:40

  2) RPC Server Acceptance Tests
       Acceptance tests
         @web-socket Acceptance Tests
           Subscribes to hts tokens and listens for synthetic log events
             @release captures approve and transferFrom events:
     Error: server response 500 Internal Server Error (request={  }, response={  }, error=null, code=SERVER_ERROR, version=6.8.1)
      at makeError (packages/server/node_modules/ethers/src.ts/utils/errors.ts:694:21)
      at assert (packages/server/node_modules/ethers/src.ts/utils/errors.ts:715:25)
      at FetchResponse.assertOk (packages/server/node_modules/ethers/src.ts/utils/fetch.ts:939:15)
      at JsonRpcProvider._send (packages/server/node_modules/ethers/src.ts/providers/provider-jsonrpc.ts:1160:18)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at /home/runner/work/hedera-json-rpc-relay/hedera-json-rpc-relay/packages/server/node_modules/ethers/src.ts/providers/provider-jsonrpc.ts:500:40
```

### Steps to reproduce

run

```
npm run acceptancetest:ws
```

### Hedera network

other

### Version

v0.36.0

### Operating system

None

**Comment by ebadiere** [comment]
Passed when running entire suite against 0.40.0-rc1 on previewnet, twice.
