### ISSUE TITLE
Insufficient TX fee 

### ISSUE THREAD

**Issue by pathornteng** [hashgraph/hedera-json-rpc-relay#1950]
### Description

Currently, when I try to submit a hbar transfer transaction, the JSON RPC relay shows the following error
```
[2023-12-04 03:19:55.289 +0000] ERROR (relay-eth/1306716 on ip-172-31-39-175): [Request ID: fefa21e3-340b-42c5-98e5-43314bef4e7f] Failed to successfully submit sendRawTransaction for transaction 0x02f8768201281d8459682f0086017988ee7700826050941b95f47e44008eac8592e5fc8ad9d62c98c8a1cf888ac7230489e8000080c080a09ee33dee8a124ab72505d7fe5538a92462268b5e46dadb0e633e9a01a901bb7aa040a6a6c3149f6f3602acc0fdbdb0f91a9cfb4a99f8bc8c4cde9a29b5cbd58ec7
    err: {
      "type": "SDKClientError",
      "message": "transaction 0.0.4530551@1701659978.213805905 failed precheck with status INSUFFICIENT_TX_FEE",
      "stack":
          Error: transaction 0.0.4530551@1701659978.213805905 failed precheck with status INSUFFICIENT_TX_FEE
              at SDKClient.<anonymous> (/home/ubuntu/hedera/hedera-json-rpc-relay/packages/relay/dist/lib/clients/sdkClient.js:115:40)
              at Generator.throw (<anonymous>)
              at rejected (/home/ubuntu/hedera/hedera-json-rpc-relay/packages/relay/dist/lib/clients/sdkClient.js:25:65)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      "status": {
        "_code": 9
      },
      "validNetworkError": true
    }
[2023-12-04 03:19:55.289 +0000] ERROR (rpc-server/1306716 on ip-172-31-39-175): [Request ID: fefa21e3-340b-42c5-98e5-43314bef4e7f] Error invoking RPC: transaction 0.0.4530551@1701659978.213805905 failed precheck with status INSUFFICIENT_TX_FEE
```

Not sure what's causing it. I also reported another issue about inaccurate gas estimation but I am not sure 100% if it's related.

### Steps to reproduce

Connect Metamask to HashIO and try to transfer Hbar to another account

### Hedera network

testnet

### Version

latest

### Operating system

None

**Comment by AlfredoG87** [comment]
Hello @pathornteng, I've done a couple tests and was able to successfully send HBAR to accounts using `MetaMask` and `HashIO` Relay, both on `Mainnet` and `Testnet`, also tried to send to existing accounts, and new accounts (hollow) so it gets auto-created when sending HBAR (Tx Fee is higher when is a hollow account, since you as the sender needs to pay for the costs of creating the account) however, I was able to send HBAR on all scenarios on both `testnet` and `mainnet`.

Could you share specific steps to be able to reproduce your issue, or also, share a script you might be using?

**Comment by pathornteng** [comment]
Ah, I think it's resolved now. It looks like the network was super overwhelmed and the congestion pricing kicked in, leading this to this error. We can park this issue for now. I will reopen if it circles back.
