### ISSUE TITLE
Foundry Fork Testing Error: Unable to Test Historical Blocks with Specified Block Number

### ISSUE THREAD

**Issue by a-ridley** [hashgraph/hedera-json-rpc-relay#1996]
### Description

Foundry supports testing in a forked environment using what they call[ Forking Mode](https://book.getfoundry.sh/forge/fork-testing#:~:text=approach%20to%20use.-,Forking%20Mode,-To%20run%20all) with the following terminal command:

`forge test --fork-url <your_rpc_url>`

I can successfully run my foundry tests in a forked Hedera testnet using Hashio.

```
> forge test --fork-url https://testnet.hashio.io/api -vvvv
[⠢] Compiling...
[⠰] Compiling 1 files with 0.8.23
[⠔] Solc 0.8.23 finished in 1.13s
Compiler run successful!

Running 2 tests for test/foundry/TodoList.t.sol:TodoListTest
[PASS] testNumberOfTodos() (gas: 9394)
Logs:
  Current number of Todos: 9

Traces:
  [9394] TodoListTest::testNumberOfTodos()
    ├─ [2325] 0x124e4d4a40bdC6FFfda736078896eD16ECf1cA32::getNumberOfTodos() [staticcall]
    │   └─ ← 9
    ├─ emit log_named_uint(key: "Current number of Todos", val: 9)
    └─ ← ()

[PASS] test_createTodo_returnsNumberOfTodosIncrementedByOne() (gas: 59166)
Traces:
  [59166] TodoListTest::test_createTodo_returnsNumberOfTodosIncrementedByOne()
    ├─ [2325] 0x124e4d4a40bdC6FFfda736078896eD16ECf1cA32::getNumberOfTodos() [staticcall]
    │   └─ ← 9
    ├─ [51026] 0x124e4d4a40bdC6FFfda736078896eD16ECf1cA32::createTodo("A new todo for you!")
    │   └─ ← 10
    └─ ← ()

Test result: ok. 2 passed; 0 failed; 0 skipped; finished in 2.89s
 
Ran 1 test suites: 2 tests passed, 0 failed, 0 skipped (2 total tests)
```

**The issue is when I try to specify a block from which to fork with `--fork-block-number`**

**See the error below:**

```
> forge test --fork-url https://testnet.hashio.io/api --fork-block-number 6386005
[⠢] Compiling...
No files changed, compilation skipped
2023-12-27T01:07:00.475866Z ERROR sharedbackend: Failed to send/recv `basic` err=failed to get account for 0x0000000000000000000000000000000000000000: (code: -32603, message: [Request ID: 4cf11fed-be6f-492f-b0c1-17c1490ac888] Unknown error invoking RPC, data: None) address=0x0000000000000000000000000000000000000000

Running 1 test for test/foundry/TodoList.t.sol:TodoListTest
[FAIL. Reason: failed to deploy contract: backend: failed while inspecting: Database error: failed to get account for 0x0000000000000000000000000000000000000000: (code: -32603, message: [Request ID: 4cf11fed-be6f-492f-b0c1-17c1490ac888] Unknown error invoking RPC, data: None)] setUp() (gas: 0)
Test result: FAILED. 0 passed; 1 failed; 0 skipped; finished in 20.49s
 
Ran 1 test suites: 0 tests passed, 1 failed, 0 skipped (1 total tests)

Failing tests:
Encountered 1 failing test in test/foundry/TodoList.t.sol:TodoListTest
[FAIL. Reason: failed to deploy contract: backend: failed while inspecting: Database error: failed to get account for 0x0000000000000000000000000000000000000000: (code: -32603, message: [Request ID: 4cf11fed-be6f-492f-b0c1-17c1490ac888] Unknown error invoking RPC, data: None)] setUp() (gas: 0)

Encountered a total of 1 failing tests, 0 tests succeeded
```

### Steps to reproduce

1. Unzip the project below and open it in vscode
[foundry-hedera-fork-testing.zip](https://github.com/hashgraph/hedera-json-rpc-relay/files/13774438/foundry-hedera-fork-testing.zip)
2. edit the .env and add in your account id and private key
3. Deploy the TodoList.sol contract using the following command:
`forge create --rpc-url https://testnet.hashio.io/api --private-key <HEX_Encoded_Private_Key> contracts/TodoList.sol:TodoList`
4. Once forge is done deploying the smart contract, in the terminal copy the `Deployed To` evm address and replace the EVM address on line 10 in the file `/test/foundry/TodoList.t.sol `
5.  I usually wait ~15 minutes after deploying to grab the contract's create transaction block number from hashscan
![Screenshot 2023-12-26 at 5 22 48 PM](https://github.com/hashgraph/hedera-json-rpc-relay/assets/18725916/009311f1-5be1-4329-a4ec-2b14b5a3cdef)
and then run the forge command to fork test at that specific block number
`forge test --fork-url https://testnet.hashio.io/api --fork-block-number 6386004`

Notice the error:

```
[⠢] Compiling...
No files changed, compilation skipped
2023-12-27T01:07:00.475866Z ERROR sharedbackend: Failed to send/recv `basic` err=failed to get account for 0x0000000000000000000000000000000000000000: (code: -32603, message: [Request ID: 4cf11fed-be6f-492f-b0c1-17c1490ac888] Unknown error invoking RPC, data: None) address=0x0000000000000000000000000000000000000000

Running 1 test for test/foundry/TodoList.t.sol:TodoListTest
[FAIL. Reason: failed to deploy contract: backend: failed while inspecting: Database error: failed to get account for 0x0000000000000000000000000000000000000000: (code: -32603, message: [Request ID: 4cf11fed-be6f-492f-b0c1-17c1490ac888] Unknown error invoking RPC, data: None)] setUp() (gas: 0)
Test result: FAILED. 0 passed; 1 failed; 0 skipped; finished in 20.49s
 
Ran 1 test suites: 0 tests passed, 1 failed, 0 skipped (1 total tests)

Failing tests:
Encountered 1 failing test in test/foundry/TodoList.t.sol:TodoListTest
[FAIL. Reason: failed to deploy contract: backend: failed while inspecting: Database error: failed to get account for 0x0000000000000000000000000000000000000000: (code: -32603, message: [Request ID: 4cf11fed-be6f-492f-b0c1-17c1490ac888] Unknown error invoking RPC, data: None)] setUp() (gas: 0)

Encountered a total of 1 failing tests, 0 tests succeeded
```

### Hedera network

testnet

### Version

"relay/0.38.0","jsonrpc":"2.0","id":"2

### Operating system

macOS

**Comment by Nana-EC** [comment]
@ebadiere please take a look

**Comment by ebadiere** [comment]
This is an intermittent problem.  The first time I compiled, deployed and ran the test on testnet, it passed.  I tried running it the next day and it failed.  I tried it later in the day and it passed.

**Comment by ebadiere** [comment]
The issue seems to be with eth_getTransactionCount.   It runs successfully when I point my relay running locally to testnet, but I get the following 400 in the console:
```
[2024-01-14 21:09:16.678 +0000] ERROR (mirror-node/64519 on Admins-Laptop.local): [Request ID: 37292566-85f8-493a-99bc-2598414bc91d] [GET] accounts/0x0000000000000000000000000000000000000000?transactiontype=ETHEREUMTRANSACTION&timestamp=lte:1705097782.716990097&limit=2&order=desc 504 status
    err: {
      "type": "Error",
      "message": "timeout of 10000ms exceeded",
      "stack":
          Error: timeout of 10000ms exceeded
              at MirrorNodeClient.handleError (/Users/user/projects/hedera-json-rpc-relay/packages/relay/dist/lib/clients/mirrorNodeClient.js:235:31)
              at MirrorNodeClient.<anonymous> (/Users/user/projects/hedera-json-rpc-relay/packages/relay/dist/lib/clients/mirrorNodeClient.js:206:22)
              at Generator.throw (<anonymous>)
              at rejected (/Users/user/projects/hedera-json-rpc-relay/packages/relay/dist/lib/clients/mirrorNodeClient.js:25:65)
    }
[2024-01-14 21:09:16.680 +0000] ERROR (rpc-server/64519 on Admins-Laptop.local): [Request ID: 37292566-85f8-493a-99bc-2598414bc91d] Request timeout. Please try again.
[2024-01-14 21:09:16.681 +0000] INFO (rpc-server/64519 on Admins-Laptop.local): [Request ID: 37292566-85f8-493a-99bc-2598414bc91d] [POST]: eth_getTransactionCount 400 (JSON RPC ERROR) 61112 ms
[2024-01-14 21:09:20.913 +0000] TRACE (mirror-node/64519 on Admins-Laptop.local):  Retry delay 200 ms on 'undefined'
[2024-01-14 21:09:31.139 +0000] TRACE (mirror-node/64519 on Admins-Laptop.local):  Retry delay 200 ms on 'undefined'
```
When running against the relay on testnet the following eth_getTransactionCount error is listed in the logs explorer:
```
{
  "textPayload": "[2024-01-14 21:05:07.331 +0000] \u001b[32mINFO\u001b[39m (rpc-server/62 on testnet-hashio-7db99f7789-fcrqt): \u001b[36m[Request ID: 2baf9d38-01d5-4cf4-bef1-e8da0550953c] [POST]: eth_getTransactionCount 500 (INTERNAL ERROR) 20026 ms\u001b[39m",
  "insertId": "fye1ygtp44x2utss",
  "resource": {
    "type": "k8s_container",
    "labels": {
      "container_name": "hedera-json-rpc-relay",
      "namespace_name": "testnet",
      "cluster_name": "hashio-external",
      "project_id": "hash-io",
      "pod_name": "testnet-hashio-7db99f7789-fcrqt",
      "location": "us-central1"
    }
  },
  "timestamp": "2024-01-14T21:05:07.341318767Z",
  "severity": "INFO",
  "labels": {
    "compute.googleapis.com/resource_name": "gke-hashio-external-default-pool-a0930315-szec",
    "k8s-pod/app_kubernetes_io/instance": "testnet-hashio",
    "k8s-pod/app": "testnet-hashio",
    "k8s-pod/app_kubernetes_io/name": "testnet-hashio",
    "k8s-pod/pod-template-hash": "7db99f7789"
  },
  "logName": "projects/hash-io/logs/stdout",
  "receiveTimestamp": "2024-01-14T21:05:10.600057476Z"
}
```

**Comment by a-ridley** [comment]
No matter what block number I provide, it looks like it always gives back the contract state from the latest block rather than from the specified historical block.

**Comment by ebadiere** [comment]
I believe the issue we're running into here is that the relay is returning stateRoot value of `"stateRoot": "0x0000000000000000000000000000000000000000000000000000000000000000"` in a JSON RPC block request, (eth_getBlockByNumber, or eth_getBlockByHash).  Without the stateRoot the state tree from that block cannot be rebuilt:
https://ethereum.stackexchange.com/questions/15317/how-ethereum-transaction-tree-is-formed.

The zero 32bytes hex value returned in the relay is by design.  We need to document that we do not support the forking at a given block.
