### ISSUE TITLE
Tests fail during the business day with `Assert transactionReceipt: 'effectiveGasPrice' should equal mirrorNode response`

### ISSUE THREAD

**Issue by ebadiere** [hashgraph/hedera-json-rpc-relay#2010]
### Description

One of the failing tests is `@release should execute "eth_getTransactionReceipt" for hash of London transaction` which calls `Assertions.transactionReceipt(res, mirrorResult, currentPrice);` which eventually checks the effect gas price with the response from the mirror node.  Other tests use this code and seem to fail mainly during the US business day.

### Steps to reproduce

1. Point the tests to testnet.  This seems to only happen on testnet.
2. Run the release tests, `npm run acceptancetest:release`.  This will take some time to complete.  You can isolate the `@release should execute "eth_getTransactionReceipt" for hash of London transaction` and use that test to investigate.  
3. These are flaky tests, so they will pass at times.  You may need to run the whole suite at different times of the day or just the single test.  You may need to experiment a bit here.

### Hedera network

testnet

### Version

v0.39.0

### Operating system

macOS

**Comment by ebadiere** [comment]
The latest run resulted in:
```
  2 pending
  2 failing

  1) RPC Server Acceptance Tests
       Acceptance tests
         @api-batch-1 RPC Server Acceptance Tests
           RPC Server Acceptance Tests
             Transaction related RPC Calls
               @release should execute "eth_getTransactionReceipt" for hash of London transaction:

      AssertionError: Assert transactionReceipt: 'effectiveGasPrice' should equal mirrorNode response: expected '960000000000' to equal '970000000000'
      + expected - actual

      -960000000000
      +970000000000

      at Function.Assertions.transactionReceipt (packages/server/tests/helpers/assertions.ts:254:10)
      at Context.<anonymous> (packages/server/tests/acceptance/rpc_batch1.spec.ts:645:20)
      at Generator.next (<anonymous>)
      at fulfilled (packages/server/tests/acceptance/rpc_batch1.spec.ts:24:58)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)

  2) RPC Server Acceptance Tests
       Acceptance tests
         @api-batch-2 RPC Server Acceptance Tests
           eth_getCode
             "before all" hook for "should execute "eth_getCode" for hts token":
     Error: transaction execution reverted (action="sendTransaction", data=null, reason=null, invocation=null, revert=null, transaction={ "data": "", "from": "0xC706f6793B2EEd9C3b228317F8351Afa09DdaBbc", "to": "0x2edDFf8B5dC81e33aB56d73c8ed3F98554Cbaac5" }, receipt={ "_type": "TransactionReceipt", "blockHash": "0xa2e4f8cd92b9b6d676a876f7add4cdf16c253e2ae0441666f083be55ca7b5a8a", "blockNumber": 6766719, "contractAddress": null, "cumulativeGasUsed": "4320000", "from": "0xC706f6793B2EEd9C3b228317F8351Afa09DdaBbc", "gasPrice": "970000000000", "gasUsed": "4000000", "hash": "0xba39625612ac8f7518f7be975d0bdfcccdedc068aab513dd0e0d09feecf30f1e", "index": 11, "logs": [  ], "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "root": null, "status": 0, "to": "0x2edDFf8B5dC81e33aB56d73c8ed3F98554Cbaac5" }, code=CALL_EXCEPTION, version=6.9.1)
      at makeError (packages/server/node_modules/ethers/src.ts/utils/errors.ts:694:21)
      at assert (packages/server/node_modules/ethers/src.ts/utils/errors.ts:715:25)
      at checkReceipt (packages/server/node_modules/ethers/src.ts/providers/provider.ts:1469:19)
      at ContractTransactionResponse.wait (packages/server/node_modules/ethers/src.ts/providers/provider.ts:1486:24)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at ContractTransactionResponse.wait (packages/server/node_modules/ethers/src.ts/contract/wrappers.ts:136:25)
```
