### ISSUE TITLE
Intermittent 502 errors when running release tests on testnet.

### ISSUE THREAD

**Issue by ebadiere** [hashgraph/hedera-json-rpc-relay#2011]
### Description

The following errors occur intermittently when running the release tests:
```
 1) RPC Server Acceptance Tests
       Acceptance tests
         @api-batch-2 RPC Server Acceptance Tests
           eth_getBalance
             @release should correctly execute "eth_getBalance" with block number in the last 15 minutes with several txs around that time:
     Error: server response 502 Bad Gateway (request={  }, response={  }, error=null, code=SERVER_ERROR, version=6.9.1)
      at makeError (packages/server/node_modules/ethers/src.ts/utils/errors.ts:694:21)
      at assert (packages/server/node_modules/ethers/src.ts/utils/errors.ts:715:25)
      at FetchResponse.assertOk (packages/server/node_modules/ethers/src.ts/utils/fetch.ts:939:15)
      at JsonRpcProvider._send (packages/server/node_modules/ethers/src.ts/providers/provider-jsonrpc.ts:1232:18)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at /Users/user/projects/hedera-json-rpc-relay/packages/server/node_modules/ethers/src.ts/providers/provider-jsonrpc.ts:537:40

  2) RPC Server Acceptance Tests
       Acceptance tests
         @api-batch-2 RPC Server Acceptance Tests
           eth_getCode
             "before all" hook for "should execute "eth_getCode" for hts token":
     Error: transaction execution reverted (action="sendTransaction", data=null, reason=null, invocation=null, revert=null, transaction={ "data": "", "from": "0x711d96bd029A74C785804B268fa4eD2F9EdD1cC1", "to": "0xa2E6265E6fCFD8A3424B7E6119F0E84A6B3596AE" }, receipt={ "_type": "TransactionReceipt", "blockHash": "0x83dcb032f6acf32fbd0ea4dea882616fc30127d99d2e60b862e13b5afbc6af6a", "blockNumber": 6763889, "contractAddress": null, "cumulativeGasUsed": "4000000", "from": "0x711d96bd029A74C785804B268fa4eD2F9EdD1cC1", "gasPrice": "960000000000", "gasUsed": "4000000", "hash": "0x30503905fbfcf39f4bc021cd298dd4f7a6e1387c6ca0acab65a99d3be7171bee", "index": 0, "logs": [  ], "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "root": null, "status": 0, "to": "0xa2E6265E6fCFD8A3424B7E6119F0E84A6B3596AE" }, code=CALL_EXCEPTION, version=6.9.1)
      at makeError (packages/server/node_modules/ethers/src.ts/utils/errors.ts:694:21)
      at assert (packages/server/node_modules/ethers/src.ts/utils/errors.ts:715:25)
      at checkReceipt (packages/server/node_modules/ethers/src.ts/providers/provider.ts:1469:19)
      at ContractTransactionResponse.wait (packages/server/node_modules/ethers/src.ts/providers/provider.ts:1486:24)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at ContractTransactionResponse.wait (packages/server/node_modules/ethers/src.ts/contract/wrappers.ts:136:25)

  3) RPC Server Acceptance Tests
       Acceptance tests
         @web-socket Acceptance Tests
           Subscribes to log events
             "before all" hook for "Subscribes for debug":
     Uncaught Error: server response 502 Bad Gateway (request={  }, response={  }, error=null, code=SERVER_ERROR, version=6.9.1)
      at makeError (packages/server/node_modules/ethers/src.ts/utils/errors.ts:694:21)
      at assert (packages/server/node_modules/ethers/src.ts/utils/errors.ts:715:25)
      at FetchResponse.assertOk (packages/server/node_modules/ethers/src.ts/utils/fetch.ts:939:15)
      at JsonRpcProvider._send (packages/server/node_modules/ethers/src.ts/providers/provider-jsonrpc.ts:1232:18)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at /Users/user/projects/hedera-json-rpc-relay/packages/server/node_modules/ethers/src.ts/providers/provider-jsonrpc.ts:537:40



[2024-01-04 17:10:32.166 +0000] INFO (rpc-acceptance-test/23450 on Admins-Laptop.hsd1.co.comcast.net): Acceptance Tests spent 1730.60724683 ℏ
[2024-01-04 17:10:32.166 +0000] INFO (rpc-acceptance-test/23450 on Admins-Laptop.hsd1.co.comcast.net): Stop relay
npm notice
npm notice New patch version of npm available! 10.2.4 -> 10.2.5
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.2.5
npm notice Run npm install -g npm@10.2.5 to update!
npm notice
➜  hedera-json-rpc-relay git:(1986-tests-are-flaky-gas-fees) ✗
```

### Steps to reproduce

1. Point to testnet.
2. Run the release tests: `npm run acceptancetest:release`

### Hedera network

testnet

### Version

v0.39.0

### Operating system

macOS

**Comment by ebadiere** [comment]
Could not reproduce.
