### ISSUE TITLE
DApp tests are not stable.

### ISSUE THREAD

**Issue by ebadiere** [hashgraph/hedera-json-rpc-relay#2029]
### Description

The Dapp tests fail intermittently both from the command line and in CI.  The latest failed with the following:
```
synpress    | Error: bad response (status=400, headers={"access-control-allow-origin":"*","access-control-allow-methods":"GET,HEAD,PUT,POST,DELETE","x-request-id":"56c70ac7-c824-42d1-b5e5-98ad9e119353","content-type":"application/json; charset=utf-8","content-length":"224","date":"Tue, 09 Jan 2024 14:56:36 GMT","connection":"close"}, body="{\"error\":{\"code\":-32001,\"name\":\"Resource not found\",\"message\":\"[Request ID: 56c70ac7-c824-42d1-b5e5-98ad9e119353] Requested resource not found. address '0x23b56EdbB39975E80284915763dbD82E55Cf0eD3'.\"},\"jsonrpc\":\"2.0\",\"id\":51}", requestBody="{\"method\":\"eth_sendRawTransaction\",\"params\":[\"0x02f9052d82012a808459682f0086014af800a700830f42408080b904d1608060405234801561001057600080fd5b506104b1806100206000396000f3fe6080604052600436106100355760003560e01c80632ccb1b301461003e578063cae6b2621461005e578063e8178a6a1461007e57005b3661003c57005b005b34801561004a57600080fd5b5061003c610059366004610335565b61009e565b34801561006a57600080fd5b5061003c610079366004610361565b61018f565b34801561008a57600080fd5b5061003c6100993660046103b2565b610279565b8047116100f15760405162461bcd60e51b815260206004820152601d60248201527f496e73756666696369656e7420636f6e74726163742062616c616e6365000000604482015260640160405180910390fd5b6040516001600160a01b038316908290600081818185875af1925050503d806000811461013a576040519150601f19603f3d011682016040523d82523d6000602084013e61013f565b606091505b5050604080513381526001600160a01b03851660208201529081018390527fd1ba4ac2e2a11b5101f6cb4d978f514a155b421e8ec396d2d9abaf0bb02917ee915060600160405180910390a15050565b6040516001600160a01b038481166024830152838116604483015260648201839052600091829187169060840160408051601f198184030181529181526020820180516001600160e01b03166323b872dd60e01b179052516101f19190610423565b6000604051808303816000865af19150503d806000811461022e576040519150601f19603f3d011682016040523d82523d6000602084013e610233565b606091505b50915091507fc939de2540668c9bbcd5df58c1a1a88520e87daddfe8f47a40c9584513d3dc8b828260405161026992919061043f565b60405180910390a1505050505050565b6040516001600160a01b038381166024830152604482018390526000919085169060640160408051601f198184030181529181526020820180516001600160e01b031663a9059cbb60e01b179052516102d29190610423565b6000604051808303816000865af19150503d806000811461030f576040519150601f19603f3d011682016040523d82523d6000602084013e610314565b606091505b50505050505050565b6001600160a01b038116811461033257600080fd5b50565b6000806040838503121561034857600080fd5b82356103538161031d565b946020939093013593505050565b6000806000806080858703121561037757600080fd5b84356103828161031d565b935060208501356103928161031d565b925060408501356103a28161031d565b9396929550929360600135925050565b6000806000606084860312156103c757600080fd5b83356103d28161031d565b925060208401356103e28161031d565b929592945050506040919091013590565b60005b8381101561040e5781810151838201526020016103f6565b8381111561041d576000848401525b50505050565b600082516104358184602087016103f3565b9190910192915050565b821515815260406020820152600082518060408401526104668160608501602087016103f3565b601f01601f191691909101606001939250505056fea2646970667358221220f30f24e7cb53cec0f19dea9429a8b0b0d0e5ee387de9de13fb9f36354c569cdc64736f6c63430008090033c0019fffee253575935d837f969d000eb4c49b262b74ab16f010bbcd0c495c1d9dc8a060e12268fe236859b785daa9ef38797705e708e68101fdcc19a61a24788612ff\"],\"id\":51,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="http://host.docker.internal:7546/", code=SERVER_ERROR, version=web/5.7.1)
synpress    |     at Logger.makeError (/app/node_modules/@ethersproject/logger/lib/index.js:238:21)
synpress    |     at Logger.throwError (/app/node_modules/@ethersproject/logger/lib/index.js:247:20)
synpress    |     at /app/node_modules/@ethersproject/providers/node_modules/@ethersproject/web/lib/index.js:275:36
synpress    |     at step (/app/node_modules/@ethersproject/providers/node_modules/@ethersproject/web/lib/index.js:33:23)
synpress    |     at Object.next (/app/node_modules/@ethersproject/providers/node_modules/@ethersproject/web/lib/index.js:14:53)
synpress    |     at fulfilled (/app/node_modules/@ethersproject/providers/node_modules/@ethersproject/web/lib/index.js:5:58)
synpress    |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
synpress    |   reason: 'bad response',
synpress    |   code: 'SERVER_ERROR',
synpress    |   status: 400,
synpress    |   headers: {
synpress    |     'access-control-allow-origin': '*',
synpress    |     'access-control-allow-methods': 'GET,HEAD,PUT,POST,DELETE',
synpress    |     'x-request-id': '56c70ac7-c824-42d1-b5e5-98ad9e119353',
synpress    |     'content-type': 'application/json; charset=utf-8',
synpress    |     'content-length': '224',
synpress    |     date: 'Tue, 09 Jan 2024 14:56:36 GMT',
synpress    |     connection: 'close'
synpress    |   },
synpress    |   body: `{"error":{"code":-32001,"name":"Resource not found","message":"[Request ID: 56c70ac7-c824-42d1-b5e5-98ad9e119353] Requested resource not found. address '0x23b56EdbB39975E80284[91](https://github.com/hashgraph/hedera-json-rpc-relay/actions/runs/7462376090/job/20305595583#step:10:92)5763dbD82E55Cf0eD3'."},"jsonrpc":"2.0","id":51}`,
synpress    |   requestBody: '{"method":"eth_sendRawTransaction","params":["0x02f9052d82012a808459682f0086014af800a700830f42408080b904d1608060405234801561001057600080fd5b506104b1806100206000396000f3fe6080604052600436106100355760003560e01c80632ccb1b301461003e578063cae6b2621461005e578063e8178a6a1461007e57005b3661003c57005b005b34801561004a57600080fd5b5061003c610059366004610335565b61009e565b34801561006a57600080fd5b5061003c610079366004610361565b61018f565b34801561008a57600080fd5b5061003c6100993660046103b2565b610279565b8047116100f15760405162461bcd60e51b815260206004820152601d60248201527f496e73756666696369656e7420636f6e74726163742062616c616e6365000000604482015260640160405180910390fd5b6040516001600160a01b038316908290600081818185875af1[92](https://github.com/hashgraph/hedera-json-rpc-relay/actions/runs/7462376090/job/20305595583#step:10:93)5050503d806000811461013a576040519150601f19603f3d011682016040523d82523d6000602084013e61013f565b606091505b5050604080513381526001600160a01b03851660208201529081018390527fd1ba4ac2e2a11b5101f6cb4d978f514a155b421e8ec396d2d9abaf0bb02917ee915060600160405180910390a15050565b6040516001600160a01b038481166024830152838116604483015260648201839052600091829187169060840160408051601f198184030181529181526020820180516001600160e01b03166323b872dd60e01b179052516101f19190610423565b6000604051808303816000865af19150503d806000811461022e576040519150601f19603f3d011682016040523d82523d6000602084013e610233565b606091505b50915091507fc939de2540668c9bbcd5df58c1a1a88520e87daddfe8f47a40c9584513d3dc8b828260405161026992919061043f565b60405180910390a1505050505050565b6040516001600160a01b038381166024830152604482018390526000919085169060640160408051601f198184030181529181526020820180516001600160e01b031663a9059cbb60e01b179052516102d29190610423565b6000604051808303816000865af19150503d806000811461030f576040519150601f19603f3d011682016040523d82523d6000602084013e610314565b606091505b50505050505050565b6001600160a01b038116811461033257600080fd5b50565b6000806040838503121561034857600080fd5b82356103538161031d565b946020939093013593505050565b6000806000806080858703121561037757600080fd5b84356103828161031d565b935060208501356103928161031d565b925060408501356103a28161031d565b9396929550929360600135925050565b6000806000606084860312156103c757600080fd5b83356103d28161031d565b925060208401356103e28161031d565b929592945050506040919091013590565b60005b8381101561040e5781810151838201526020016103f6565b8381111561041d576000848401525b50505050565b600082516104358184602087016103f3565b9190910192915050565b821515815260406020820152600082518060408401526104668160608501602087016103f3565b601f01601f191691909101606001939250505056fea2646970667358221220f30f24e7cb53cec0f19dea9429a8b0b0d0e5ee387de9de13fb9f36354c569cdc64736f6c63430008090033c0019fffee253575935d837f969d000eb4c49b262b74ab16f010bbcd0c495c1d9dc8a060e12268fe236859b785daa9ef38797705e708e68101fdcc19a61a24788612ff"],"id":51,"jsonrpc":"2.0"}',
synpress    |   requestMethod: 'POST',
synpress    |   url: 'http://host.docker.internal:7546',
synpress    |   transaction: {
synpress    |     type: 2,
synpress    |     chainId: 298,
synpress    |     nonce: 0,
synpress    |     maxPriorityFeePerGas: BigNumber { _hex: '0x59682f00', _isBigNumber: true },
synpress    |     maxFeePerGas: BigNumber { _hex: '0x014af800a700', _isBigNumber: true },
synpress    |     gasPrice: null,
synpress    |     gasLimit: BigNumber { _hex: '0x0f4240', _isBigNumber: true },
synpress    |     to: null,
synpress    |     value: BigNumber { _hex: '0x00', _isBigNumber: true },
synpress    |     data: '0x608060405234801561001057600080fd5b506104b1806100206000396000f3fe6080604052600436106100355760003560e01c80632ccb1b301461003e578063cae6b2621461005e578063e8178a6a1461007e57005b3661003c57005b005b34801561004a57600080fd5b5061003c61005[93](https://github.com/hashgraph/hedera-json-rpc-relay/actions/runs/7462376090/job/20305595583#step:10:94)66004610335565b61009e565b34801561006a57600080fd5b5061003c610079366004610361565b61018f565b34801561008a57600080fd5b5061003c6100993660046103b2565b610279565b8047116100f15760405162461bcd60e51b815260206004820152601d60248201527f496e73756666696369656e7420636f6e74726163742062616c616e6365000000604482015260640160405180910390fd5b6040516001600160a01b038316908290600081818185875af1925050503d806000811461013a576040519150601f19603f3d011682016040523d82523d6000602084013e61013f565b606091505b5050604080513381526001600160a01b03851660208201529081018390527fd1ba4ac2e2a11b5101f6cb4d978f514a155b421e8ec396d2d9abaf0bb02917ee915060600160405180910390a15050565b6040516001600160a01b038481166024830152838116604483015260648201839052600091829187169060840160408051601f198184030181529181526020820180516001600160e01b03166323b872dd60e01b179052516101f19190610423565b6000604051808303816000865af19150503d806000811461022e576040519150601f19603f3d011682016040523d82523d6000602084013e610233565b606091505b50915091507fc939de2540668c9bbcd5df58c1a1a88520e87daddfe8f47a40c9584513d3dc8b828260405161026992919061043f565b60405180910390a1505050505050565b6040516001600160a01b038381166024830152604482018390526000919085169060640160408051601f198184030181529181526020820180516001600160e01b031663a9059cbb60e01b179052516102d29190610423565b6000604051808303816000865af19150503d806000811461030f576040519150601f19603f3d011682016040523d82523d6000602084013e610314565b606091505b50505050505050565b6001600160a01b038116811461033257600080fd5b50565b6000806040838503121561034857600080fd5b82356103538161031d565b946020939093013593505050565b6000806000806080858703121561037757600080fd5b84356103828161031d565b935060208501356103928161031d565b925060408501356103a28161031d565b9396929550929360600135925050565b6000806000606084860312156103c757600080fd5b83356103d28161031d565b925060208401356103e28161031d565b929592945050506040919091013590565b60005b8381101561040e5781810151838201526020016103f6565b8381111561041d576000848401525b50505050565b600082516104358184602087016103f3565b9190910192915050565b821515815260406020820152600082518060408401526104668160608501602087016103f3565b601f01601f191691909101606001939250505056fea2646970667358221220f30f24e7cb53cec0f19dea9429a8b0b0d0e5ee387de9de13fb9f36354c569cdc64736f6c63430008090033',
synpress    |     accessList: [],
synpress    |     hash: '0x30a6233ea6d5cb1c678059abef53f0f4c849b19cc32be23faf3f3646f3c74da8',
synpress    |     v: 1,
synpress    |     r: '0x00ffee253575935d837f969d000eb4c49b262b74ab16f010bbcd0c4[95](https://github.com/hashgraph/hedera-json-rpc-relay/actions/runs/7462376090/job/20305595583#step:10:96)c1d9dc8',
synpress    |     s: '0x60e12268fe236859b785daa9ef38797705e708e68101fdcc19a61a24788612ff',
synpress    |     from: '0x23b56EdbB39[97](https://github.com/hashgraph/hedera-json-rpc-relay/actions/runs/7462376090/job/20305595583#step:10:98)5E80284915763dbD82E55Cf0eD3',
synpress    |     confirmations: 0
synpress    |   },
synpress    |   transactionHash: '0x30a6233ea6d5cb1c678059abef53f0f4c849b19cc32be23faf3f3646f3c74da8'
synpress    | }
synpress    | 
synpress    | Node.js v18.12.1
synpress exited with code 1
Stopping display  ... 
Stopping display  ... done
1
Aborting on container exit...

```

### Steps to reproduce

1. Run the Dapp tests from the command line. or....
2. Push up a PR and observe the initial DApp tests run.  It rarely passes on the first run.

### Hedera network

other

### Version

v0.30.0

### Operating system

macOS

**Comment by Ferparishuertas** [comment]
Blocked by DApp contibuity decision
