### ISSUE TITLE
API Batch 3 is a flaky test.

### ISSUE THREAD

**Issue by ebadiere** [hashgraph/hedera-json-rpc-relay#2568]
### Description

It fails in the snyk with the following:
```
  1) RPC Server Acceptance Tests
       Acceptance tests
         @api-batch-3 RPC Server Acceptance Tests
           eth_getTransactionCount
             "before all" hook for "@release should execute "eth_getTransactionCount" primary":
     Error: max attempts of 10 was reached for request with last error being: GrpcServiceError: gRPC service failed with status: TIMEOUT
      at CostQuery.execute (packages/server/node_modules/@hashgraph/sdk/lib/Executable.cjs:675:11)
      at AccountInfoQuery.getCost (packages/server/node_modules/@hashgraph/sdk/lib/query/Query.cjs:186:18)
      at AccountInfoQuery._beforeExecute (packages/server/node_modules/@hashgraph/sdk/lib/query/Query.cjs:296:26)
      at AccountInfoQuery.execute (packages/server/node_modules/@hashgraph/sdk/lib/Executable.cjs:528:5)
      ```
It also timed out multiple times in the workflow security update [PR.](https://github.com/hashgraph/hedera-json-rpc-relay/pull/2565)

### Steps to reproduce

Run it in CI.

### Hedera network

other

### Version

v0.49.0

### Operating system

Linux

**Comment by quiet-node** [comment]
Batch 3 seems to improve in recent PRs with the update from local-node and the SDK. Closing but will still keep an eye on this item

**Comment by quiet-node** [comment]
Batch 3 is still observed failing on PRs
