### ISSUE TITLE
SmartContract execution Gateway Time-out

### ISSUE THREAD

**Issue by insider89** [hashgraph/hedera-json-rpc-relay#2581]
### Description

We are running our own mirror node(0.103.0) and hedera json-rpc-relay(0.48.0). 

We are using hardhat to execute ERC20 contract on hedera network(testnet).

Time to time we have an error:
```Batch #1
  Executing GenericERC20Module#GenericERC20...

An unexpected error occurred:

ProviderError: Gateway Time-out
    at HttpProvider.request (/home/coder/usecase/node_modules/hardhat/src/internal/core/providers/http.ts:90:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async EIP1193JsonRpcClient.sendTransaction (/home/coder/usecase/node_modules/@nomicfoundation/ignition-core/src/internal/execution/jsonrpc-client.ts:418:24)
    at async sendTransactionForOnchainInteraction (/home/coder/usecase/node_modules/@nomicfoundation/ignition-core/src/internal/execution/future-processor/helpers/network-interaction-execution.ts:204:18)
    at async sendTransaction (/home/coder/usecase/node_modules/@nomicfoundation/ignition-core/src/internal/execution/future-processor/handlers/send-transaction.ts:85:18)
    at async FutureProcessor.processFuture (/home/coder/usecase/node_modules/@nomicfoundation/ignition-core/src/internal/execution/future-processor/future-processor.ts:114:9)
    at async ExecutionEngine._executeBatch (/home/coder/usecase/node_modules/@nomicfoundation/ignition-core/src/internal/execution/execution-engine.ts:153:30)
    at async ExecutionEngine.executeModule (/home/coder/usecase/node_modules/@nomicfoundation/ignition-core/src/internal/execution/execution-engine.ts:114:25)
    at async Deployer.deploy (/home/coder/usecase/node_modules/@nomicfoundation/ignition-core/src/internal/deployer.ts:194:25)
    at async SimpleTaskDefinition.action (/home/coder/usecase/node_modules/@nomicfoundation/hardhat-ignition/src/index.ts:302:24)
```

This happens when `eth_sendRawTransaction` execution time more than 15000ms. If it's less than 15000ms I got successfully response from json-rpc-relay, if above 15000ms - `Gateway Time-out`. But, even if I got a time-out, in the hedera explorer I see that the contract was executed successfully.

In the logs I see, that before finish `eth_sendRawTransaction` call, `getContractResult` repeated multiple times.
```
[Request ID: 52de2ae2-6061-430e-a7ba-d399271f25ea] Repeating request getContractResult with args ["0.0.4393826-1717761215-367655450"] retry count 0 of 20. Waiting 200 ms before repeating request
[2024-06-07 11:53:44.150 +0000] DEBUG (mirror-node/62 on hedera-testnet-relay-hedera-json-rpc-relay-65f7bbc8fd-plppb): [Request ID: 52de2ae2-6061-430e-a7ba-d399271f25ea] [GET] contracts/results/0.0.4393826-1717761215-367655450 404 status
[2024-06-07 11:53:44.150 +0000] TRACE (mirror-node/62 on hedera-testnet-relay-hedera-json-rpc-relay-65f7bbc8fd-plppb): [Request ID: 52de2ae2-6061-430e-a7ba-d399271f25ea] Repeating request getContractResult with args ["0.0.4393826-1717761215-367655450"] retry count 1 of 20. Waiting 200 ms before repeating request
[2024-06-07 11:53:44.471 +0000] DEBUG (mirror-node/62 on hedera-testnet-relay-hedera-json-rpc-relay-65f7bbc8fd-plppb): [Request ID: 52de2ae2-6061-430e-a7ba-d399271f25ea] [GET] contracts/results/0.0.4393826-1717761215-367655450 404 status
[2024-06-07 11:53:44.471 +0000] TRACE (mirror-node/62 on hedera-testnet-relay-hedera-json-rpc-relay-65f7bbc8fd-plppb): [Request ID: 52de2ae2-6061-430e-a7ba-d399271f25ea] Repeating request getContractResult with args ["0.0.4393826-1717761215-367655450"] retry count 2 of 20. Waiting 200 ms before repeating request
[2024-06-07 11:53:44.757 +0000] DEBUG (mirror-node/62 on hedera-testnet-relay-hedera-json-rpc-relay-65f7bbc8fd-plppb): [Request ID: 52de2ae2-6061-430e-a7ba-d399271f25ea] [GET] contracts/results/0.0.4393826-1717761215-367655450 404 status
[2024-06-07 11:53:44.757 +0000] TRACE (mirror-node/62 on hedera-testnet-relay-hedera-json-rpc-relay-65f7bbc8fd-plppb): [Request ID: 52de2ae2-6061-430e-a7ba-d399271f25ea] Repeating request getContractResult with args ["0.0.4393826-1717761215-367655450"] retry count 3 of 20. Waiting 200 ms before repeating request
[2024-06-07 11:53:45.047 +0000] DEBUG (mirror-node/62 on hedera-testnet-relay-hedera-json-rpc-relay-65f7bbc8fd-plppb): [Request ID: 52de2ae2-6061-430e-a7ba-d399271f25ea] [GET] contracts/results/0.0.4393826-1717761215-367655450 404 status
[2024-06-07 11:53:45.047 +0000] TRACE (mirror-node/62 on hedera-testnet-relay-hedera-json-rpc-relay-65f7bbc8fd-plppb): [Request ID: 52de2ae2-6061-430e-a7ba-d399271f25ea] Repeating request getContractResult with args ["0.0.4393826-1717761215-367655450"] retry count 4 of 20. Waiting 200 ms before repeating request
[2024-06-07 11:53:45.334 +0000] DEBUG (mirror-node/62 on hedera-testnet-relay-hedera-json-rpc-relay-65f7bbc8fd-plppb): [Request ID: 52de2ae2-6061-430e-a7ba-d399271f25ea] [GET] contracts/results/0.0.4393826-1717761215-367655450 404 status
[2024-06-07 11:53:45.334 +0000] TRACE (mirror-node/62 on hedera-testnet-relay-hedera-json-rpc-relay-65f7bbc8fd-plppb): [Request ID: 52de2ae2-6061-430e-a7ba-d399271f25ea] Repeating request getContractResult with args ["0.0.4393826-1717761215-367655450"] retry count 5 of 20. Waiting 200 ms before repeating request
[2024-06-07 11:53:45.634 +0000] DEBUG (mirror-node/62 on hedera-testnet-relay-hedera-json-rpc-relay-65f7bbc8fd-plppb): [Request ID: 52de2ae2-6061-430e-a7ba-d399271f25ea] [GET] contracts/results/0.0.4393826-1717761215-367655450 404 status
[2024-06-07 11:53:45.634 +0000] TRACE (mirror-node/62 on hedera-testnet-relay-hedera-json-rpc-relay-65f7bbc8fd-plppb): [Request ID: 52de2ae2-6061-430e-a7ba-d399271f25ea] Repeating request getContractResult with args ["0.0.4393826-1717761215-367655450"] retry count 6 of 20. Waiting 200 ms before repeating request
[2024-06-07 11:53:45.921 +0000] DEBUG (mirror-node/62 on hedera-testnet-relay-hedera-json-rpc-relay-65f7bbc8fd-plppb): [Request ID: 52de2ae2-6061-430e-a7ba-d399271f25ea] [GET] contracts/results/0.0.4393826-1717761215-367655450 404 status
[2024-06-07 11:53:45.921 +0000] TRACE (mirror-node/62 on hedera-testnet-relay-hedera-json-rpc-relay-65f7bbc8fd-plppb): [Request ID: 52de2ae2-6061-430e-a7ba-d399271f25ea] Repeating request getContractResult with args ["0.0.4393826-1717761215-367655450"] retry count 7 of 20. Waiting 200 ms before repeating request
[2024-06-07 11:53:46.207 +0000] DEBUG (mirror-node/62 on hedera-testnet-relay-hedera-json-rpc-relay-65f7bbc8fd-plppb): [Request ID: 52de2ae2-6061-430e-a7ba-d399271f25ea] [GET] contracts/results/0.0.4393826-1717761215-367655450 404 status
...
[Request ID: 52de2ae2-6061-430e-a7ba-d399271f25ea] Repeating request getContractResult with args ["0.0.4393826-1717761215-367655450"] retry count 13 of 20. Waiting 200 ms before repeating request
...
[Request ID: 52de2ae2-6061-430e-a7ba-d399271f25ea] caching getContractResult.0.0.4393826-1717761215-367655450:{"address":"0x2a24a81bed265ff1fadb815fc0bea7e496d359f5","amount":0,"bloom":"0x00000000000000000000000000000000000000000000000000800000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000000000008000000000001000000000000000000000000000000000000020000000000000200000800000000000000000000000010000000400000000000000000000000000000000000000000000000000000000000000000000000000000040000000000000000000000200000000000000000000000000000000002000000000000000000000000000000080400000000000000000020000000000000000000000000000000000000000000000000000000000000000000","call_result": ...
...
[Request ID: 52de2ae2-6061-430e-a7ba-d399271f25ea] [POST]: eth_sendRawTransaction 200 16241 ms
```

My json-rpc-relay config:
```
values: {
          replicaCount: 1,
          config: {
            CHAIN_ID: '0x128',
            HEDERA_NETWORK: 'testnet',
            MIRROR_NODE_URL: args.mirrorNodeUrl,
            OPERATOR_ID_MAIN: args.operatorIdMain || '',
            OPERATOR_KEY_MAIN: args.operatorIdKey || '',
            MIRROR_NODE_GET_CONTRACT_RESULTS_RETRIES: '20',
            MIRROR_NODE_RETRY_DELAY: '200'
          },
          image: {
            // will be deleted after new helm chart release
            tag: '0.48.0'
          }
        }
```

Is there any reason why `eth_sendRawTransaction` take so long? Maybe I need to change some configuration to improve execution time?

### Steps to reproduce

1. Deploy testnet mirror node.
2. Deploy json-rpc-relay and point it to testnet mirror node.
3. Execute erc20 contract.

### Hedera network

testnet

### Version

v0.48.0

### Operating system

None

**Comment by insider89** [comment]
Found that envoy proxy has 15s timeout. By increasing it, we have fixed the issue. But still unclear, why `eth_sendRawTransaction` take so much time to execute.
