### ISSUE TITLE
`--env` picked up but `--env-file` not picked up when run via Docker

### ISSUE THREAD

**Issue by bguiz** [hashgraph/hedera-json-rpc-relay#2656]
### Description

- Works: Run docker image of RPC relay with individually set `--env` flags
- Does not work: Run docker image of RPC relay with a single `--env-file` flag

### Steps to reproduce

(1) Create a dot-env file named `.rpcrelay.env`, like the following. (substitute your own account ID and private key)

```shell
HEDERA_NETWORK="testnet"
OPERATOR_ID_MAIN="0.0.1534"
OPERATOR_KEY_MAIN="0x<redacted>"
CHAIN_ID="0x128"
MIRROR_NODE_URL="https://testnet.mirrornode.hedera.com/"
```

(2) Run the following command:

```shell
docker run \
    --rm \
    --publish 7546:7546 \
    --env-file ./.rpcrelay.env \
    ghcr.io/hashgraph/hedera-json-rpc-relay:${VERSION_TAG}
 ```

This results in an error indicating that one or more of the env vars were not passed into the RPC relay server.
See {ERROR_1} in additional context below

(3) Run the following alternative command:

```shell
set -a
source ./.rpcrelay.env
set +a
docker run \
    --rm \
    --publish 7546:7546 \
    --env HEDERA_NETWORK=${HEDERA_NETWORK} \
    --env OPERATOR_ID_MAIN=${OPERATOR_ID_MAIN} \
    --env OPERATOR_KEY_MAIN=${OPERATOR_KEY_MAIN} \
    --env CHAIN_ID=${CHAIN_ID} \
    --env MIRROR_NODE_URL=${MIRROR_NODE_URL} \
    ghcr.io/hashgraph/hedera-json-rpc-relay:${VERSION_TAG}
```

This time the RPC relay server does appear to pick up the env vars correctly, and runs properly.
Even though (2) and (3) should be functionally equivalent.

(4) For sanity checking purposes run this command:

```shell
docker run \
    --rm \
    --publish 7546:7546 \
    --env-file ./.rpcrelay.env \
    ghcr.io/hashgraph/hedera-json-rpc-relay:${VERSION_TAG} env
```

That outputs the environment variables, and the ones in the `.rpcrelay.env` are indeed there.

### Additional context

{ERROR_1}

```text
[2024-07-02 14:19:35.404 +0000] INFO (relay/85 on 845c1654b6cd): Configurations successfully loaded
/home/node/app/node_modules/@hashgraph/cryptography/lib/PrivateKey.cjs:168
    throw new _BadKeyError.default(`private key cannot be decoded from bytes: ${message}`);
    ^

BadKeyError: private key cannot be decoded from bytes: Cannot read properties of null (reading 'fromRed')
    at PrivateKey.fromBytes (/home/node/app/node_modules/@hashgraph/cryptography/lib/PrivateKey.cjs:168:11)
    at PrivateKey.fromString (/home/node/app/node_modules/@hashgraph/cryptography/lib/PrivateKey.cjs:195:23)
    at PrivateKey.fromStringDer (/home/node/app/packages/relay/node_modules/@hashgraph/sdk/lib/PrivateKey.cjs:161:51)
    at HAPIService.createPrivateKeyBasedOnFormat (/home/node/app/packages/relay/dist/lib/services/hapiService/hapiService.js:175:41)
    at HAPIService.initClient (/home/node/app/packages/relay/dist/lib/services/hapiService/hapiService.js:157:35)
    at new HAPIService (/home/node/app/packages/relay/dist/lib/services/hapiService/hapiService.js:41:32)
    at new RelayImpl (/home/node/app/packages/relay/dist/lib/relay.js:60:29)
    at Object.<anonymous> (/home/node/app/packages/server/dist/server.js:68:15)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)

Node.js v18.18.2
npm ERR! Lifecycle script `start` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: @hashgraph/json-rpc-server@0.50.2 
npm ERR!   at location: /home/node/app/packages/server 
lerna ERR! npm run start exited 1 in '@hashgraph/json-rpc-server'
lerna ERR! npm run start exited 1 in '@hashgraph/json-rpc-server'
```

### Hedera network

testnet

### Version

0.50.2

### Operating system

macOS

**Comment by bguiz** [comment]
This appears to be related to the way that Docker parses an env file

This does not work:
```shell
HEDERA_NETWORK="testnet"
OPERATOR_ID_MAIN="0.0.1534"
OPERATOR_KEY_MAIN="0x<redacted>"
CHAIN_ID="0x128"
MIRROR_NODE_URL="https://testnet.mirrornode.hedera.com/"
```

However, this does:
```shell
HEDERA_NETWORK=testnet
OPERATOR_ID_MAIN=0.0.1534
OPERATOR_KEY_MAIN=0x<redacted>
CHAIN_ID=0x128
MIRROR_NODE_URL=https://testnet.mirrornode.hedera.com/
```

(The difference is the presence of quotes)

Note that when a `.env` file is supplied and RPC relay server is run *without* docker, both of the above work the same.

Thus this appears to be a bug in docker (or least an undocumented inconsistency), and nothing to do with RPC relay.
