### ISSUE TITLE
Verify consistent passes of acceptance tests against previewnet/testnet

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-json-rpc-relay#340]
### Problem

Some inconsistencies have been viewed when running the aceptance test, mainly aagainst public envs.
This is likely since the TPS in production envs differs from local envs.
In local node we're in control of all submitted transactions but in production w need to be able to handle change state w regards to block and transaction details.

This may prevent the adoption of fully automated tests for each release.

The following tests have been seen to sometimes return different than expected values
- `eth_gasPrice` 
- `eth_getBlockByNumber`
- `eth_getBlockByHash`

The following tests sometimes return errors 
- `eth_getTransactionReceipt`
- `eth_sendRawTransaction`

Below is an example unsuccessful run
Note: I filtered out  a subset of tests by adding `@release` text and running `./node_modules/ts-mocha/bin/ts-mocha ./packages/server/tests/acceptance/index.spec.ts  -g @release --exit`
Full logs also attached
```
  38 passing (2m)
  8 failing

  1) RPC Server Acceptance Tests
       Acceptance tests
         RPC Server Acceptance Tests
           RPC Server Acceptance Tests
             Block related RPC calls
               @release should execute "eth_getBlockByHash", hydrated transactions = true:

      AssertionError: expected '0x14cf2a45c00' to equal '0xa7a3582000'
      + expected - actual

      -0x14cf2a45c00
      +0xa7a3582000

      at Function.block (packages/server/tests/helpers/assertions.ts:62:51)
      at Context.<anonymous> (packages/server/tests/acceptance/rpc.spec.ts:269:28)
      at Generator.next (<anonymous>)
      at fulfilled (packages/server/tests/acceptance/rpc.spec.ts:24:58)

  2) RPC Server Acceptance Tests
       Acceptance tests
         RPC Server Acceptance Tests
           RPC Server Acceptance Tests
             Block related RPC calls
               @release should execute "eth_getBlockByNumber", hydrated transactions = true:

      AssertionError: expected '0x14cf2a45c00' to equal '0xa7a3582000'
      + expected - actual

      -0x14cf2a45c00
      +0xa7a3582000

      at Function.block (packages/server/tests/helpers/assertions.ts:62:51)
      at Context.<anonymous> (packages/server/tests/acceptance/rpc.spec.ts:294:28)
      at Generator.next (<anonymous>)
      at fulfilled (packages/server/tests/acceptance/rpc.spec.ts:24:58)

  3) RPC Server Acceptance Tests
       Acceptance tests
         RPC Server Acceptance Tests
           RPC Server Acceptance Tests
             Block related RPC calls
               @release should call eth_gasPrice:

      AssertionError: expected '0x14cf2a45c00' to equal '0xa7a3582000'
      + expected - actual

      -0x14cf2a45c00
      +0xa7a3582000

      at Context.<anonymous> (packages/server/tests/acceptance/rpc.spec.ts:793:32)
      at Generator.next (<anonymous>)
      at fulfilled (packages/server/tests/acceptance/rpc.spec.ts:24:58)

  4) RPC Server Acceptance Tests
       Acceptance tests
         RPC Server Acceptance Tests
           RPC Server Acceptance Tests
             Block related RPC calls
               Transaction related RPC Calls
                 @release should execute "eth_getTransactionReceipt" for hash of legacy transaction:
     Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":58,\"error\":{\"code\":-32009,\"name\":\"Gas price too low\",\"message\":\"Gas price below configured minimum gas price\"}}", error={"code":-32009}, requestBody="{\"method\":\"eth_sendRawTransaction\",\"params\":[\"0xf86c8085a7a3582000832dc6c0940000000000000000000000000000000002d768878502540be40080820273a03dc20c0b12ae0e3e387127ea9878a4738d155700bf997bddfff8f809235021a8a073a7fe9524fc1b4de71b5eedfb297024a6d2d23eb8302acc61cbc73c09a05f0f\"],\"id\":58,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://testnet.hashio.io/api", code=SERVER_ERROR, version=web/5.6.1)
      at Logger.makeError (node_modules/@ethersproject/logger/src.ts/index.ts:261:28)
      at Logger.throwError (node_modules/@ethersproject/logger/src.ts/index.ts:273:20)
      at /.../hedera-json-rpc-relay/node_modules/@ethersproject/providers/node_modules/@ethersproject/web/src.ts/index.ts:329:28
      at step (node_modules/@ethersproject/providers/node_modules/@ethersproject/web/lib/index.js:33:23)
      at Object.next (node_modules/@ethersproject/providers/node_modules/@ethersproject/web/lib/index.js:14:53)
      at fulfilled (node_modules/@ethersproject/providers/node_modules/@ethersproject/web/lib/index.js:5:58)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  5) RPC Server Acceptance Tests
       Acceptance tests
         RPC Server Acceptance Tests
           RPC Server Acceptance Tests
             Block related RPC calls
               Transaction related RPC Calls
                 @release should execute "eth_getTransactionReceipt" for hash of London transaction:
     Request failed with status code 404


  6) RPC Server Acceptance Tests
       Acceptance tests
         RPC Server Acceptance Tests
           RPC Server Acceptance Tests
             Block related RPC calls
               Transaction related RPC Calls
                 @release should execute "eth_sendRawTransaction" for legacy EIP 155 transactions:
     Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":64,\"error\":{\"code\":-32009,\"name\":\"Gas price too low\",\"message\":\"Gas price below configured minimum gas price\"}}", error={"code":-32009}, requestBody="{\"method\":\"eth_sendRawTransaction\",\"params\":[\"0xf86c0185a7a3582000832dc6c0940000000000000000000000000000000002d768878502540be40080820274a00ffe93784dff2214bac03311e3efb4d0ae5045810b11ac026a1ca69f15326464a01f89ba5600f5cc0b85806fc615a9314bbcdb3cc0f081c4b9a200e83d884bd65a\"],\"id\":64,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://testnet.hashio.io/api", code=SERVER_ERROR, version=web/5.6.1)
      at Logger.makeError (node_modules/@ethersproject/logger/src.ts/index.ts:261:28)
      at Logger.throwError (node_modules/@ethersproject/logger/src.ts/index.ts:273:20)
      at /...hedera-json-rpc-relay/node_modules/@ethersproject/providers/node_modules/@ethersproject/web/src.ts/index.ts:329:28
      at step (node_modules/@ethersproject/providers/node_modules/@ethersproject/web/lib/index.js:33:23)
      at Object.next (node_modules/@ethersproject/providers/node_modules/@ethersproject/web/lib/index.js:14:53)
      at fulfilled (node_modules/@ethersproject/providers/node_modules/@ethersproject/web/lib/index.js:5:58)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  7) RPC Server Acceptance Tests
       Acceptance tests
         RPC Server Acceptance Tests
           RPC Server Acceptance Tests
             Block related RPC calls
               Transaction related RPC Calls
                 @release should execute "eth_getTransactionByHash" for existing transaction:
     Request failed with status code 404


  8) RPC Server Acceptance Tests
       Acceptance tests
         RPC Server Acceptance Tests
           RPC Server Acceptance Tests
             Gas Price related RPC endpoints
               @release should call eth_feeHistory with updated fees:
     AssertionError: expected undefined to exist
      at Function.feeHistory (packages/server/tests/helpers/assertions.ts:182:37)
      at Context.<anonymous> (packages/server/tests/acceptance/rpc.spec.ts:1076:28)
      at Generator.next (<anonymous>)
      at fulfilled (packages/server/tests/acceptance/rpc.spec.ts:24:58)
```

[releaseTestnetTest.log](https://github.com/hashgraph/hedera-json-rpc-relay/files/9113364/releaseTestnetTest.log)

### Solution

Verify acceptance tests consistently pass when pointed to previewnet and testnet.
Where failures are viewed let's capture tickets to address in next sprint.

### Alternatives

_No response
_

**Comment by Ivo-Yankov** [comment]
I am seeing this error while executing against previewnet:
```
[2022-07-19 07:18:05.842 +0000] TRACE (relay-eth/13298 on ivo-HP-ProBook): (BUG) RequestType.fromCode() does not handle code: 86
    err: {
      "type": "Error",
      "message": "(BUG) RequestType.fromCode() does not handle code: 86",
      "stack":
          Error: (BUG) RequestType.fromCode() does not handle code: 86
              at Function._fromCode (/home/ivo/projects/hedera-json-rpc-relay/packages/relay/node_modules/@hashgraph/sdk/lib/RequestType.cjs:496:11)
              at Function._fromProtobuf (/home/ivo/projects/hedera-json-rpc-relay/packages/relay/node_modules/@hashgraph/sdk/lib/TransactionFeeSchedule.cjs:86:102)
              at /home/ivo/projects/hedera-json-rpc-relay/packages/relay/node_modules/@hashgraph/sdk/lib/FeeSchedule.cjs:78:159
              at Array.map (<anonymous>)
              at Function._fromProtobuf (/home/ivo/projects/hedera-json-rpc-relay/packages/relay/node_modules/@hashgraph/sdk/lib/FeeSchedule.cjs:78:111)
              at Function._fromProtobuf (/home/ivo/projects/hedera-json-rpc-relay/packages/relay/node_modules/@hashgraph/sdk/lib/FeeSchedules.cjs:76:90)
              at Function.fromBytes (/home/ivo/projects/hedera-json-rpc-relay/packages/relay/node_modules/@hashgraph/sdk/lib/FeeSchedules.cjs:65:25)
              at SDKClient.<anonymous> (/home/ivo/projects/hedera-json-rpc-relay/packages/relay/dist/lib/clients/sdkClient.js:203:39)
              at Generator.next (<anonymous>)
              at fulfilled (/home/ivo/projects/hedera-json-rpc-relay/packages/relay/dist/lib/clients/sdkClient.js:24:58)
              at runMicrotasks (<anonymous>)
              at processTicksAndRejections (node:internal/process/task_queues:96:5)
    }

```
