### ISSUE TITLE
eth_getTransactionCount throwing error for "latest" block

### ISSUE THREAD

**Issue by mok0230** [hashgraph/hedera-json-rpc-relay#516]
### Description

I am trying to make a call to fetch the account's nonce. This same call has been successful the last couple months, but now an error is being thrown:

```
await ethers.provider.getTransactionCount("0x205399a519d341051e86e790aaa0f713340745ca", "latest")

ProviderError: [Request ID: 411f508d-d821-4097-901e-61f45f1a2141] Unknown error invoking RPC
    at HttpProvider.request (/Users/danmckeon/Documents/dev/hedera-contracts/node_modules/hardhat/src/internal/core/providers/http.ts:78:19)
    at LocalAccountsProvider.request (/Users/danmckeon/Documents/dev/hedera-contracts/node_modules/hardhat/src/internal/core/providers/accounts.ts:188:34)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at EthersProviderWrapper.send (/Users/danmckeon/Documents/dev/hedera-contracts/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
```

### Steps to reproduce

Configure the Hedera Testnet JSON RPC Relay as an `ethers.provider` and then run:

```
async function getTxCount() {
  try {
    await ethers.provider.getTransactionCount("0x205399a519d341051e86e790aaa0f713340745ca", "latest")
  } catch (e) {
    console.error('error', e)
  }
}

getTxCount();
```

### Hedera network

testnet

### Version

v0.7.0

### Operating system

macOS

**Comment by Nana-EC** [comment]
Thanks, we observed and resolved this in the single deployed instance where it occurred.
This was not a relay issue and was specific to deployment infrastructure.
