### ISSUE TITLE
Transfer HBAR with Metamask mobile app not working

### ISSUE THREAD

**Issue by georgi-l95** [hashgraph/hedera-json-rpc-relay#602]
### Description

Transferring HBAR from one account to another not working. Transaction stuck on pending, cannot be cancelled.
Error from relay: 

```
[2022-10-07 13:06:43.331 +0000] ERROR (rpc-server/47868 on Georgis-MacBook-Pro-4.local): [Request ID: 2b6e5f3c-7ab0-48c5-9281-e9ce55998d83] [POST] eth_getTransactionByHash: -32603 65 ms
    err: {
      "type": "TypeError",
      "message": "Cannot read properties of undefined (reading 'toString')",
      "stack":
          TypeError: Cannot read properties of undefined (reading 'toString')
              at Function.numberTo0x (/Users/georgi-lazarov/Documents/GitHub/hedera-json-rpc-relay/packages/relay/dist/lib/eth.js:892:68)
              at EthImpl.<anonymous> (/Users/georgi-lazarov/Documents/GitHub/hedera-json-rpc-relay/packages/relay/dist/lib/eth.js:819:43)
              at Generator.next (<anonymous>)
              at fulfilled (/Users/georgi-lazarov/Documents/GitHub/hedera-json-rpc-relay/packages/relay/dist/lib/eth.js:24:58)
              at processTicksAndRejections (node:internal/process/task_queues:96:5)
    }
[2022-10-07 13:06:43.332 +0000] ERROR (rpc-server/47868 on Georgis-MacBook-Pro-4.local): returning error to sender: [Request ID: 2b6e5f3c-7ab0-48c5-9281-e9ce55998d83] Unknown error invoking RPC
```

### Steps to reproduce

- Start local node
- Add two of the accounts in your metamask
- Transfer HBAR from one to the other

### Hedera network

other

### Version

v5.8.0

### Operating system

macOS

**Comment by Nana-EC** [comment]
I just verified 0.9.0-rc2 in testnet and there's no issue.
Curious to see what's special about the transaction causing the undefined issue.

**Comment by georgi-l95** [comment]
Not sure, I import two accounts from those initially created when local-node is started. I've tried restarting the node and relay, reseting metamask. Issue still persist on my machine. Transfer with other accounts apart from those (created when local node is started) are working.

**Comment by georgi-l95** [comment]
Cannot reproduce anymore.
