### ISSUE TITLE
`null` value returned for `amount` by MirrorNode for contract result queries

### ISSUE THREAD

**Issue by dimitrovmaksim** [hashgraph/hedera-json-rpc-relay#710]
### Description

The relay break with 
```
   err: {
      "type": "TypeError",
      "message": "Cannot read properties of null (reading 'toString')",
      "stack":
          TypeError: Cannot read properties of null (reading 'toString')
              at Function.numberTo0x (/Users/maksimdimitrov/Projects/hedera/hedera-json-rpc-relay/packages/relay/dist/lib/eth.js:948:41)
              at /Users/maksimdimitrov/Projects/hedera/hedera-json-rpc-relay/packages/relay/dist/lib/eth.js:1139:40
              at runMicrotasks (<anonymous>)
              at processTicksAndRejections (node:internal/process/task_queues:96:5)
    }
```
for contract result queries
https://testnet.mirrornode.hedera.com/api/v1/contracts/0x0000000000000000000000000000000000004320/results/1599360484.445086003

I suspect the culprit here is the `amount` property being `null`

I'm not sure if this is by design or is an issue in the mirror-node and if it should be resolved here or in the mirror-node

### Steps to reproduce

https://testnet.mirrornode.hedera.com/api/v1/contracts/0x0000000000000000000000000000000000004320/results/1599360484.445086003

### Hedera network

testnet

### Version

0.11.0

**Comment by Nana-EC** [comment]
@dimitrovmaksim according to [contrctFunctionResult.amount](https://github.com/hashgraph/hedera-protobufs/blob/main/services/contract_call_local.proto#L141) the mirror node will have a null [contractResult.amount](https://github.com/hashgraph/hedera-mirror-node/blob/main/hedera-mirror-rest/viewmodel/contractResultViewModel.js#L39) for `ContractCreate` and `ContractCall` since these currently don't send HBARs in the form of direct transfers.

The relay should handle this and set [transaction.value](https://github.com/hashgraph/hedera-json-rpc-relay/blob/main/packages/relay/src/lib/eth.ts#L987) as 0 in these cases.
I think we can do this with a `value: EthImpl.numberTo0x(contractResult.amount),` -> `value: EthImpl.nullableNumberTo0x(contractResult.amount),` change.
