### ISSUE TITLE
`eth_sendRawTransaction` returns error against testnet

### ISSUE THREAD

**Issue by georgi-l95** [hashgraph/hedera-json-rpc-relay#914]
### Description

When trying to run hardhat example, from tools, against testnet most of the times it fails with error:
```
1) RPC
       should be able to transfer hbars between two accounts:
     [Request ID: 8aed0916-599c-452a-947c-9ebc9d5803e9] Unknown error invoking RPC
  ProviderError: HttpProviderError
      at HttpProvider.request (/Users/georgi-lazarov/Documents/GitHub/example-hardhat-project/node_modules/hardhat/src/internal/core/providers/http.ts:78:19)
      at LocalAccountsProvider.request (/Users/georgi-lazarov/Documents/GitHub/example-hardhat-project/node_modules/hardhat/src/internal/core/providers/accounts.ts:181:36)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at EthersProviderWrapper.send (/Users/georgi-lazarov/Documents/GitHub/example-hardhat-project/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
```
After debugging I've found that we actually get error from `eth_sendRawTransaction`
This is the request:

```
{
  jsonrpc: "2.0",
  method: "eth_sendRawTransaction",
  params: [
    "0x02f906b682012881ed80860126ad20e84083061a808080b9065c608060405234801561001057600080fd5b506040516105fc3803806105fc83398101604081905261002f9161015f565b8051610042906000906020840190610080565b507fad181ee258ff92d26bf7ed2e6b571ef1cba3afc45f028b863b0f02adaffc2f0681604051610072919061020b565b60405180910390a150610279565b82805461008c9061023e565b90600052602060002090601f0160209004810192826100ae57600085556100f4565b82601f106100c757805160ff19168380011785556100f4565b828001600101855582156100f4579182015b828111156100f45782518255916020019190600101906100d9565b50610100929150610104565b5090565b5b808211156101005760008155600101610105565b634e487b7160e01b600052604160045260246000fd5b60005b8381101561014a578181015183820152602001610132565b83811115610159576000848401525b50505050565b60006020828403121561017157600080fd5b81516001600160401b038082111561018857600080fd5b818401915084601f83011261019c57600080fd5b8151818111156101ae576101ae610119565b604051601f8201601f19908116603f011681019083821181831017156101d6576101d6610119565b816040528281528760208487010111156101ef57600080fd5b61020083602083016020880161012f565b979650505050505050565b602081526000825180602084015261022a81604085016020870161012f565b601f01601f19169190910160400192915050565b600181811c9082168061025257607f821691505b6020821081141561027357634e487b7160e01b600052602260045260246000fd5b50919050565b610374806102886000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c8063a41368621461003b578063cfae321714610050575b600080fd5b61004e6100493660046101fd565b61006e565b005b6100586100bc565b60405161006591906102ae565b60405180910390f35b805161008190600090602084019061014e565b507fad181ee258ff92d26bf7ed2e6b571ef1cba3afc45f028b863b0f02adaffc2f06816040516100b191906102ae565b60405180910390a150565b6060600080546100cb90610303565b80601f01602080910402602001604051908101604052809291908181526020018280546100f790610303565b80156101445780601f1061011957610100808354040283529160200191610144565b820191906000526020600020905b81548152906001019060200180831161012757829003601f168201915b5050505050905090565b82805461015a90610303565b90600052602060002090601f01602090048101928261017c57600085556101c2565b82601f1061019557805160ff19168380011785556101c2565b828001600101855582156101c2579182015b828111156101c25782518255916020019190600101906101a7565b506101ce9291506101d2565b5090565b5b808211156101ce57600081556001016101d3565b634e487b7160e01b600052604160045260246000fd5b60006020828403121561020f57600080fd5b813567ffffffffffffffff8082111561022757600080fd5b818401915084601f83011261023b57600080fd5b81358181111561024d5761024d6101e7565b604051601f8201601f19908116603f01168101908382118183101715610275576102756101e7565b8160405282815287602084870101111561028e57600080fd5b826020860160208301376000928101602001929092525095945050505050565b600060208083528351808285015260005b818110156102db578581018301518582016040015282016102bf565b818111156102ed576000604083870101525b50601f01601f1916929092016040019392505050565b600181811c9082168061031757607f821691505b6020821081141561033857634e487b7160e01b600052602260045260246000fd5b5091905056fea264697066735822122067128c3a12bb69e61659040811ca1e6a90a4e2a04bb27fdc0eb4aec7b91f316964736f6c634300080900330000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000b696e697469616c5f6d7367000000000000000000000000000000000000000000c001a092828a9b8e24d7715cd6a333eb08af6aae1575ca4f121ec31cd3da3d74739bfba004e00b3537193273071fccd8723034741c8c6e4501a629e5fdf094e0f65a25a8",
  ],
  id: 25,
}
```

This is the response:

```
{
  jsonrpc: "2.0",
  id: 25,
  error: {
    code: -32603,
    name: "Internal error",
    message: "[Request ID: 29952384-ad60-49d6-b699-3d9807ab833b] Unknown error invoking RPC",
  },
}
```

### Steps to reproduce

1. Run test from [here](https://github.com/hashgraph/hedera-json-rpc-relay/tree/main/tools/hardhat-example), against testnet hashIO

### Hedera network

testnet, previewnet

### Version

latest

### Operating system

None

**Comment by georgi-l95** [comment]
No longer reproducible.
