### ISSUE TITLE
size limit on contract transactions

### ISSUE THREAD

**Issue by mshakeg** [hashgraph/hedera-json-rpc-relay#980]
### Description

There appears to be a size limit on `eth_sendRawTransaction` specifically affecting contract call transactions(i.e. NOT contract deploys).

`eth_call`(i.e. static calls) of the same size limit have no issue.

### Steps to reproduce

1. Checkout to the branch in [this PR](https://github.com/mshakeg/hedera-json-rpc-relay/pull/18)
2. Run the `./test/multicaller.test.ts` script against the hardhat node: `npm run test:multicaller` and observe all test cases pass.
3. Now run the script against the hedera local node; after starting the local node run: `npm run test:multicaller:local` and observe all test cases except for the following 2 fail:
    i. `should be able to make 1500 or more multicall processLongInput transactions`
    ii. `should be able to make 135 or more multicall processLongInput transactions`
In particular observe that the following 2 test cases pass:
    * `should be able to make 1500 or more multicall processLongInput calls` - unlike (i.) does a static call(not transaction) indicating no issue with `eth_call` on length 1500
    * `should be able to make 134 or more multicall processLongInput transactions` - is 1 less than (ii.) which does 135 iterations to construct the input

### Hedera network

other

### Version

@hashgraph/hedera-local@2.5.1

### Operating system

None

**Comment by ebadiere** [comment]
I ran this against the local relay, infura, and alchemy.  The same test failed on each:
Local Relay:
```
  1) Multicaller
       should be able to make 1500 or more multicall processLongInput transactions:
     ProviderError: [Request ID: 87feb184-eddc-4003-bdb0-406dd6808604] Transaction gas limit '15383176' exceeds block gas limit '15000000'
      at HttpProvider.request (/Users/user/projects/mshakeg/hedera-json-rpc-relay/tools/hardhat-example/node_modules/hardhat/src/internal/core/providers/http.ts:88:21)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async EthersProviderWrapper.send (/Users/user/projects/mshakeg/hedera-json-rpc-relay/tools/hardhat-example/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
```
Infura:
```
  1) Multicaller
       should be able to make 1500 or more multicall processLongInput transactions:
     ProviderError: oversized data: transaction size 480186, limit 131072
      at HttpProvider.request (/Users/user/projects/mshakeg/hedera-json-rpc-relay/tools/hardhat-example/node_modules/hardhat/src/internal/core/providers/http.ts:88:21)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async EthersProviderWrapper.send (/Users/user/projects/mshakeg/hedera-json-rpc-relay/tools/hardhat-example/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)

```
Alchemy:
```
  1) Multicaller
       should be able to make 1500 or more multicall processLongInput transactions:
     ProviderError: oversized data: transaction size 480184, limit 131072
      at HttpProvider.request (/Users/user/projects/mshakeg/hedera-json-rpc-relay/tools/hardhat-example/node_modules/hardhat/src/internal/core/providers/http.ts:88:21)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async EthersProviderWrapper.send (/Users/user/projects/mshakeg/hedera-json-rpc-relay/tools/hardhat-example/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
```

**Comment by mshakeg** [comment]
@ebadiere it's been a while since I created this issue, does the following test case pass on the hedera local node?

> should be able to make 135 or more multicall processLongInput transactions

**Comment by ebadiere** [comment]
Yes,
`
✔ should be able to make 135 or more multicall processLongInput transactions (9303ms)
`

**Comment by mshakeg** [comment]
ok, in that case, I think we can close this issue as when I initially created this issue that test case failed. If 1500 calls also fail on Infura and Alchemy(on Ethereum?) due to a transaction size limit then I don't think this is an issue for Hedera.
